### ISSUE TITLE
Can you update an example of the Arduino platform LLCC68? Thank you!

### ISSUE THREAD

**Issue by topmy** [jgromes/RadioLib#1012]
Can you update an example of the Arduino UNO platform LLCC68? Thank you!

**Comment by jgromes** [comment]
I don't understand what is this asking about, mostly because no issue template was followed.

Do you want examples for LLCC68? If so, why? There is no difference in usage from SX126x (and very slight configuration differences).

**Comment by jgromes** [comment]
Closed due to inactivity.
