### ISSUE TITLE
Feature request: AX.25 parser

### ISSUE THREAD

**Issue by ploeffler** [jgromes/RadioLib#1071]
ax.25 frames can be created and sent, but not received

would be a big benefit to be able to create ax.25 "servers" to be connected to

**Comment by jgromes** [comment]
Duplicate of #569 - see that issue for the current state and the roadblocks I have hit when attempting to implement this.

**Comment by ploeffler** [comment]
are we both aware of the fact, that ax.25 is not aprs?
--
Disclaimer: May be opened and read by the NSA, CIA, GCHQ, KGB, BND, and
whoever else it may NOT concern.


Am So., 21. Apr. 2024 um 17:25 Uhr schrieb Jan Gromeš <
***@***.***>:

**Comment by jgromes** [comment]
And are we both aware that APRS uses AX.25 frames?

**Comment by ploeffler** [comment]
Yes, we are!
--
Disclaimer: May be opened and read by the NSA, CIA, GCHQ, KGB, BND, and
whoever else it may NOT concern.


Am So., 21. Apr. 2024 um 17:44 Uhr schrieb Jan Gromeš <
***@***.***>:
