### ISSUE TITLE
SIM800C module support 

### ISSUE THREAD

**Issue by ricsun432** [jgromes/RadioLib#109]
I would like to have a GSM library so that I could send a file to the Internet with the LoRa module 1272x. I am specifically using an Adafruit feather 32u4 with LoRa. Thank you.

**Comment by jgromes** [comment]
SIM800 support was being worked on (see the [development branch](https://github.com/jgromes/RadioLib/tree/development/src/modules)), however, it is not a priority right now.

I will accept PRs for this purpose.

**Comment by jgromes** [comment]
Closing because SIM800 no longer really fits with the overall direction of the library, which mostly deals with RF modules that can be "hacked" to do stuff like RTTY or SSTV.
