### ISSUE TITLE
RadioLib receive function returning strings containing garbage data

### ISSUE THREAD

**Issue by Bambofy** [jgromes/RadioLib#11]
Hi,

I have switched to using char*'s instead of String objects. But the function provided as

```
for (int i = 0; i < 25; i++)
{
     char rxTransmission[20];
     int state = LORA.receive(rxTransmission, 20);

    if (state == ERR_NONE)
    {
          Serial.println(rxTransmission);
     }
}
```

returns data like this:

> HELLOWORLD☐?☐?

when sent transmissions of:

> HELLOWORLD

Any ideas?

Thanks,
Richard

-- edit -- 

When using it in this mode:
```

char rxTransmission[64];

for (int i = 0; i < 25; i++)
{
    int state = lora.receive(rxTransmission, 20);
    if (state == ERR_NONE)
    {
        Serial.println(rxTransmission)
    }
}

```
The result is "HELLOWORLDD"

**Comment by jgromes** [comment]
Null terminator for C-strings was missing from the `receive` method, fixed in 7cb5f83cc49d8dddfe29753ff7c673dadcf79637
