### ISSUE TITLE
Undocumented register sx1262

### ISSUE THREAD

**Issue by mrx23dot** [jgromes/RadioLib#1142]
I recorded SPI comm in this project 
https://github.com/meshtastic/firmware/issues/4193
which uses RadioLib for sx1262

```
0D 8C00 10 00 25 01 00 CMD_WriteRegister
0D 8C00 10 00 FF 01 00 CMD_WriteRegister
```

and couldn't find reference to register `8C00 `in this entire repo, should expect to be here 
https://github.com/jgromes/RadioLib/blob/33480235d61210a38c9c7e0c60291fce16132ff2/src/modules/SX126x/SX126x.h

**Comment by jgromes** [comment]
Well ... why don't you ask over at Meshtastic? Or better yet, understand where this command is coming from, before firing random questions? You have provided zero context, I don't know under what circumstances this is happening (and I don't expect Meshtastic maintainers will either).

RadioLib is a driver, in some confgiruations it will let you write into arbitrary register address.
