### ISSUE TITLE
LinkCheck & DeviceTime

### ISSUE THREAD

**Issue by jo-ei** [jgromes/RadioLib#1150]
Hi,
I can't get a successful response from TTN when I request LinkCheck and/or DeviceTime

node.sendMacCommandReq(RADIOLIB_LORAWAN_MAC_DEVICE_TIME);
node.sendMacCommandReq(RADIOLIB_LORAWAN_MAC_LINK_CHECK);

on TTN i can see an error "
![grafik](https://github.com/jgromes/RadioLib/assets/30876983/ed42e3c5-73e1-4a7b-a8a8-d32d3deed157)

device LoRaWAN version: 1.0.1

if I schedule a downlink with data, the data is transported correctly

Where can I query the network time for my device?

Thank you

**Comment by StevenCellist** [comment]
Hi @jo-ei, you should configure your device as LoRaWAN v1.1, not v1.0.1. Then it'll work just fine :)
