### ISSUE TITLE
startTransmit make data arg constant

### ISSUE THREAD

**Issue by dizcza** [jgromes/RadioLib#1156]
All `startTransmit` functions should accept the constant `uint8_t* data`.

I've gone through their implementation but am still not sure if I can safely cast my constant data buffer to be modifiable and expect that it won't be changed inside the `startTransmit` functionality.

**Comment by jgromes** [comment]
No modifications to the user buffer are done within `startTransmit`, so yes, `const uint8_t* data` is the more proper way to go.

**Comment by jgromes** [comment]
Added in the mentioned commit - this is likely going to cause a new minor release as the public API has changed in a way that may throw some people off.
