### ISSUE TITLE
 LLCC68

### ISSUE THREAD

**Issue by Eugene-long** [jgromes/RadioLib#1193]
**IMPORTANT: Before submitting an issue, please check the following:**
1. **Read [CONTRIBUTING.md](https://github.com/jgromes/RadioLib/blob/master/CONTRIBUTING.md)!** Issues that do not follow this document will be closed/locked/deleted/ignored.
2. RadioLib has a [Troubleshooting Guide](https://github.com/jgromes/RadioLib/wiki/Troubleshooting-Guide) Wiki page and an extensive [API documentation](https://jgromes.github.io/RadioLib/). You might find a solution to your issue there.
3. Make sure you're using the latest release of the library! Releases can be found [here](https://github.com/jgromes/RadioLib/releases).
4. Use [Arduino forums](https://forum.arduino.cc/) to ask generic questions about wireless modules, wiring, usage, etc. Only create issues for problems specific to RadioLib!
5. Error codes, their meaning and how to fix them can be found on [this page](https://jgromes.github.io/RadioLib/group__status__codes.html).

**Sketch that is causing the module fail**

```c++
paste the sketch here, even if it is an unmodified example code
```

**Hardware setup**
Wiring diagram, schematic, pictures etc.

**Debug mode output**
Enable the appropriate [debug levels](https://github.com/jgromes/RadioLib/wiki/Debug-mode) and paste the Serial monitor output here. For debugging protocols, enable `RADIOLIB_DEBUG_PROTOCOL`. For debugging issues with the radio module itself, enable `RADIOLIB_DEBUG_SPI`.

**Additional info (please complete):**
 - MCU: [e.g. Arduino Uno, ESP8266 etc.]
 - Link to Arduino core: [e.g. https://github.com/stm32duino/Arduino_Core_STM32 when using official STM32 core. See readme for links to all supported cores]
 - Wireless module type [e.g. CC1101, SX1268, etc.]
 - Arduino IDE version  [e.g. 1.8.5]
 - Library version [e.g. 3.0.0]

**Comment by Eugene-long** [comment]
Is LLCC68 supported? Can I get any example?

Eugene

**Comment by jgromes** [comment]
It is, as can be seen from:

1. The list of supported modules in the readme: https://github.com/jgromes/RadioLib?tab=readme-ov-file#supported-modules
2. The source code: https://github.com/jgromes/RadioLib/tree/master/src/modules/LLCC68
3. Existing issues: https://github.com/jgromes/RadioLib/issues?q=llcc68

There are no dedicated examples for it because it is an SX126x with a more limited configuration, but it behaves exactly the same. Just replace `SX1262` with `LLCC68` in the SX126x examples.

**Comment by Eugene-long** [comment]
TU 73!
