### ISSUE TITLE
How can I change the sync word?

### ISSUE THREAD

**Issue by t351206** [jgromes/RadioLib#122]
In the Wiki there is no information about the sync word - how can I change it?

**Comment by jgromes** [comment]
You haven't mentioned which module are you using, so the answer will have to be generic:

1. The API is consistent across different modules, so I suggest trying `setSyncword()`.

2. Almost all modules have a Settings example (for example [SX127x](https://github.com/jgromes/RadioLib/blob/master/examples/SX127x/SX127x_Settings/SX127x_Settings.ino)) that shows how to change all the basic parameters - including sync word.

3. There's a full documentation available on the [GitHub pages](https://jgromes.github.io/RadioLib/), which has information on every single class and method implemented in RadioLib.

**Comment by t351206** [comment]
thanks
