### ISSUE TITLE
SX1272 reset pin inverted

### ISSUE THREAD

**Issue by sjd227** [jgromes/RadioLib#124]
Looking at the sx1272 datasheet, it looks like reset is done by pulling the reset pin **HIGH** for 100 microseconds, then releasing it **LOW**:

<img width="1015" alt="sx1272_reset_snip" src="https://user-images.githubusercontent.com/6798187/76654404-7a206380-6530-11ea-9516-4097956a5d60.png">

But in sx127x.cpp it seems reversed:

```
void SX127x::reset() {
     Module::pinMode(_mod->getRst(), OUTPUT);
     Module::digitalWrite(_mod->getRst(), LOW);
     delayMicroseconds(100);
     Module::digitalWrite(_mod->getRst(), HIGH);
     delay(5);
}
```
Thoughts?

- Steven

**Comment by jgromes** [comment]
It looks like SX1272 has a positive-logic reset (RST=1 to reset), while SX1278 has negative logic (NRST=0 to reset). The current implementation will work for for SX1276/77/78/79, though not for SX1272/73. Will fix asap.

**Comment by jgromes** [comment]
Fixed in c1c991acc831cbb457cf96037eb9cf4ced261a6f, will release the fix as 3.4.0.  Thanks for reporting!

**Comment by sjd227** [comment]
Sounds good, thanks!

**Comment by naggie** [comment]
This explains a lot. Thanks @sjd227 and @jgromes . Definitely encountered this
