### ISSUE TITLE
class c for lorawan sx12XX

### ISSUE THREAD

**Issue by areytechai** [jgromes/RadioLib#1247]
can you add class c support pleaes

**Comment by jgromes** [comment]
We most likely can. Whether we _will_ or not, that's a different question. At the moment I don't see an immediate use-case for it, and you have not provided one. Why should we invest our time into implementing a requested feature when you have clearly invested so little of yours into this request?

I also find it both hilarious and somewhat sad that in more than seven years of being on this platform, you have yet to figure out how to write good issues - or at least ones that do not contain spelling mistakes. The first issue in LoRaLib was opened by you, and it was so bad I still remember it 7 years later.
