### ISSUE TITLE
[LoRaWAN] timeUntilUplink returns 0 when called immediately after a activateOTAA

### ISSUE THREAD

**Issue by MortenGuldager** [jgromes/RadioLib#1254]
I’ve noticed `node.timeUntilUplink()` returns 0 immediately after calling `node.activateOTAA()`. My understanding is that, especially in the case of a failed join attempt, subsequent retries should still respect duty cycle limits before the node can attempt another uplink. However, the immediate 0 return seems to suggest that the node is ready to send again right away, regardless of whether the join was successful or not.

That said, I might be misunderstanding how this behavior is expected to work. If this is the intended functionality, I'd appreciate any clarification on how to properly handle the timing of OTAA join retries.

using: esp32, radiolib7.0.0, platformio, rfm95

**Comment by StevenCellist** [comment]
Fair shout, the time-on-air of a JoinRequest is not tracked. I will pick this up.

**Comment by HeadBoffin** [comment]
> If this is the intended functionality, I'd appreciate any clarification on how to properly handle the timing of OTAA join retries.

As clarified above, it's not intended functionality and you can just stick to the duty cycle limitations, but the "proper way" is outlined in TR007 which you can find on the LoRa Alliance website.

The real world answer is that much of it is a bit academic and a whole chunk of error handling that needs to be tested & debugged when a carefully provisioned device in an area with adequate gateway coverage will join once. So don't get too tied up with backoff - keep the calculations simple and move on.

**Comment by StevenCellist** [comment]
@MortenGuldager should be resolved in upstream. Please let me know if the problem persists.
