### ISSUE TITLE
morse code tone frequency???

### ISSUE THREAD

**Issue by csurf** [jgromes/RadioLib#128]
I tried using the included morse examples in order to generate morse tones with an RFM96* module. However, it doesn't actually produce tones; it simply produces a non-audible tone that breaks squelch. Is there a way to create an audible morse tone at an arbitrary frequency (via a basic on/off pin toggle to emulate a sine wave at a specific audible frequency)???

FYI, I've managed to achieve this type of audible modulation with an SI4432-based module (RFM22B), by putting the module into "direct mode" and creating a toggled/PWM signal on a 'direct'-input pin. Is something like this possible with the sx127* ???

**Comment by jgromes** [comment]
The way Morse code is implemented is just by outputting unmodulated carrier wave, so if you demodulate it as CW, you can then decode the Morse code symbols (e.g. using Fldigi) - don't know if this can be used in your application, you haven't provided much information about it.

RFM9x/SX127x has a similar direct mode as Si4432. This mode is active when `MorseClient` is running, so you should be able to just apply PWM to get tones: https://www.youtube.com/watch?v=a0CyXdC6qJg

**Comment by jgromes** [comment]
Closed due to inactivity.
