### ISSUE TITLE
Ability to force RADIOLIB_BUILD_GENERIC instead of RADIOLIB_BUILD_ARDUINO

### ISSUE THREAD

**Issue by juanboro** [jgromes/RadioLib#1318]
Hi,
Is it possible to override RadioLib automatically setting RADIOLIB_BUILD_ARDUINO being defined when ARDUINO is defined?

The problem I have is when building RadioLib with [esphome](https://esphome.io/) with the Arduino platform - which I'm currently doing for a CC1101 device as a remote receiver [here](https://github.com/juanboro/esphome-radiolib-cc1101/).  I want to provide a HAL [specific to esphome](https://github.com/juanboro/esphome-radiolib-cc1101/blob/main/EHRLHal.h).  However, when building with the Arduino platform, BuildOpt.h is automatically determining to build with Arduino and include the Arduino hal and SPI support.

The current work around I am using is [here](https://github.com/juanboro/RadioLib/commit/42ae00b7a371f720b7a14c1cdac7c89c2b18c759).  I'm not sure if this is a good way to do this or not.

Another alternative might be for BuildOpt to detect if it is building in EspHome... but I have no idea if/how that could be done.

**Comment by jgromes** [comment]
> Is it possible to override RadioLib automatically setting RADIOLIB_BUILD_ARDUINO being defined when ARDUINO is defined?

Not in any straight-forward way. It checks whether it is being built in Arduino 1.0.0+ environment with this:

https://github.com/jgromes/RadioLib/blob/9d9d480a4828ca041f1389bb21a6a572710211f4/src/BuildOpt.h#L117-L125

So the only way would be to make sure it is not defined with some undefs, and I'd strongly advise against that.

However - are you sure you need to do this? You can always add you custom HAL, even if Arduino is enabled. The only thing "Arduino support" does is it adds the existing Arduino HAL + some Arduino-specific interfaces (such as `String`). But you can always create an instance of `Module` with you custom HAL.

**Comment by juanboro** [comment]
> However - are you sure you need to do this? You can always add you custom HAL, even if Arduino is enabled. The only thing "Arduino support" does is it adds the existing Arduino HAL + some Arduino-specific interfaces (such as `String`). 

That is what I was originally doing... it works fine for non Arduino platforms - but not when the ESPhome platform is Arduino - because they purposely are excluding SPI.h (I would assume because they want their own HAL used).  
>But you can always create an instance of `Module` with you custom HAL.

Yes - that is what I am doing --- but the problem is ArduinoHal still evaluates all the SPI stuff which won't compile (on Arduino platform) because BuildOpt.h is setting RADIOLIB_BUILD_ARDUINO

An undef of ARDUINO is bad for sure... but what I'm asking for is something like what I just put into this PR: https://github.com/jgromes/RadioLib/pull/1319 - which lets me in force the generic platform in the platformio compile options.   I'd guess there could be issues with that... another alternative might be if somehow the SPISettings / include of SPI.h could be made conditional in ArduinoHal

**Comment by jgromes** [comment]
> but the problem is ArduinoHal still evaluates all the SPI stuff which won't compile

So ... the actual root cause is that the Arduino SPI library does not compile in esphome? Is it really a good idea then to be trying to work around that?

**Comment by jgromes** [comment]
Just quickly going through esphome source seems to be using the Arduino SPI library, e.g. here: https://github.com/esphome/esphome/blob/b29c1194089f4770b7a3e9ab99b12ac890c3e2cb/esphome/components/spi/spi.h#L13

So that seems to imply SPI can be compiled with esphome. I would suggest to revisit some of your assumptions.

To be frank I'm very against adding workarounds for issues without really understanding them. This also applies to #1319. The clean solution would be to add esphome as another Arduino platform and do any necessary customization there. But until we can show that the default Arduino SPI really is causing issues in esphome (as in - prevents compilation), then I don't think it's good idea to add workarounds for things that may not even be an issue but rather some problem e.g. in the build configuration.

**Comment by juanboro** [comment]
Ok - I agree/understand... and thank you for checking --- It caused me to do some more googling, and I found [this](https://techoverflow.net/2020/12/14/how-to-fix-platformio-esp8266-esp32-fatal-error-spi-h-no-such-file-or-directory/#:~:text=This%20problem%20is%20common%20using%20the%20TFT_eSPI%20library.,to%20your%20platformio.ini%3A%20and%20recompile%20your%20source%20code.).  Adjusting the platformio build options did the trick for esphome and it now compiles :-) --- without the workaround.  I guess I have some more reading/learning to do about the whole platformio build env/libraries.

Thank you for taking the time to look at this - and sorry about the needless request.

**Comment by jgromes** [comment]
No worries - I'm glad my resistance to change ended up pointing you in the right direction :)
