### ISSUE TITLE
Regional Parameters Typo in "LoRaWAN: Device setup on TTN" Wiki

### ISSUE THREAD

**Issue by Zep0** [jgromes/RadioLib#1334]
Hi,
there is a newer version of the equivalent note, where the revision number of the regional parameters is fixed. 

Instead of:

> RadioLib uses Regional Parameters 1.1 revision 1.1. 

it now says:

> RadioLib uses RP001 Regional Parameters 1.1 revision A.

Source: 
https://github.com/jgromes/RadioLib/wiki/LoRaWAN:-Device-setup-on-TTN
https://github.com/jgromes/RadioLib/blob/master/examples/LoRaWAN/LoRaWAN_Starter/notes.md

**Comment by StevenCellist** [comment]
[Talking about consistency](https://github.com/TheThingsNetwork/lorawan-stack/issues/2784#issuecomment-648735723).... this is a proper mess. But at least I'll make these two match each other.

**Comment by StevenCellist** [comment]
Actually, upon further inspection, I added a slight modification such that RadioLib properly corresponds to 1.1 revision B instead of revision A. All mentions in this repository have been updated to reflect this change, although it's practically identical to revision A.
