### ISSUE TITLE
Conflicting ways to set payload length in implicit header mode with SX127X

### ISSUE THREAD

**Issue by snowrodeo** [jgromes/RadioLib#1345]
To set an SX127x device to use implicit headers, you need to use
setImplicit(payloadLength)

However, when putting the device into receive mode, you need to also set the payload length or it will default to 0 and overwrite the previously set value

Request that setReceive use the value from setImplicit instead of requiring an arg

**Comment by jgromes** [comment]
This is indeed a bit of an oversight - I think we can handle this similarly to how `startReceive` behaves in exaplicit mode: If the length is set to 0, it will use the previously configured implicit length. Otherwise, the length will be overwritten. Will this match your use case?

**Comment by snowrodeo** [comment]
That would work great.  Thanks!

From: Jan Gromeš ***@***.***>
Date: Saturday, December 14, 2024 at 5:40 AM
To: jgromes/RadioLib ***@***.***>
Cc: Erik Olson ***@***.***>, Author ***@***.***>
Subject: Re: [jgromes/RadioLib] Conflicting ways to set payload length in implicit header mode with SX127X (Issue #1345)

This is indeed a bit of an oversight - I think we can handle this similarly to how startReceive behaves in exaplicit mode: If the length is set to 0, it will use the previously configured implicit length. Otherwise, the length will be overwritten. Will this match your use case?

**Comment by jgromes** [comment]
Implemented in the commit above.
