### ISSUE TITLE
Clarification needed for RADIOLIB_CC1101_MAX_PACKET_LENGTH and RADIOLIB_CC1101_PACKET_LENGTH.

### ISSUE THREAD

**Issue by jofab-hub** [jgromes/RadioLib#1347]
Hi,

I would like some clarification. In [modules/CC1101/CC1101.h](https://github.com/jgromes/RadioLib/blob/master/src/modules/CC1101/CC1101.h) there is a constant (line 11): 
`#define RADIOLIB_CC1101_MAX_PACKET_LENGTH                       63
`

(I suspect that  it is the maximum size of a packet, I suspect also that this value includes the preamble). However, later in the file, (line 95), there is another definition: 

`#define RADIOLIB_CC1101_PACKET_LENGTH                           0xFF        //  7     0   packet length in bytes
`

So I do not know how to interpret these values: `RADIOLIB_CC1101_PACKET_LENGTH>RADIOLIB_CC1101_MAX_PACKET_LENGTH` (I do not know also, if it is a RadioLib limitation or a physical limit of the c1101 module).

In the example ([https://github.com/jgromes/RadioLib/blob/master/examples/CC1101/CC1101_Transmit_Interrupt/CC1101_Transmit_Interrupt.ino](https://github.com/jgromes/RadioLib/blob/master/examples/CC1101/CC1101_Transmit_Interrupt/CC1101_Transmit_Interrupt.ino)), it is also confusing. Line 75, it is written:

```
// you can transmit C-string or Arduino string up to
// 64 characters long
  transmissionState = radio.startTransmit("Hello World!");

// you can also transmit byte array up to 64 bytes long

```
But later, line 118:
```
// send another one
    Serial.print(F("[CC1101] Sending another packet ... "));

// you can transmit C-string or Arduino string up to
// 256 characters long
    String str = "Hello World! #" + String(count++);
    transmissionState = radio.startTransmit(str);

// you can also transmit byte array up to 256 bytes long
```
who should I believe? Can I send more than 63 or 64 bytes in a packet?

Thank you

**Comment by jgromes** [comment]
This is indeed a bit confusing - likely some copy-paste erros that have crept in from other radios. CC1101 only has 64-byte FIFO buffers (unlike e.g. SX127x which has 256-byte FIFO). So you can transmit and receive at most 64 bytes in a single packet using CC1101. 

I cleaned up the examples and the header file to prevent this confusion in the future - thanks for reporting!
