### ISSUE TITLE
[SX128x_BLE_Modem] Unable set Access Address, code -20.

### ISSUE THREAD

**Issue by mrninhvn** [jgromes/RadioLib#135]
![sx1280_error](https://user-images.githubusercontent.com/30751439/79534200-214e6880-80a4-11ea-95fd-bc74c4ac1ad9.JPG)

 - MCU: Arduino Uno.
 - Wireless module type: SX1280 (LAMBDA80C)
 - Arduino IDE version: 1.8.10.
 - Library version: 3.5.0.

**Comment by jgromes** [comment]
Looks like in an attempt to save on code duplicity, I used `setSyncWord` to set the access address. Obviously that method will fail for BLE modem - outsmarted by my own library :)

I also noticed there was a missing check for BLE modem in `startTransmit`, so that returned -20 as well.

Both should be fixed now - thanks for reporting!

**Comment by mrninhvn** [comment]
@jgromes Hmm I encountered CRC error when receive. Can you help me?

**Comment by jgromes** [comment]
It isn't entirely clear how CRC is processed in BLE mode, and there's also the PDU header to consider. SX128x doesn't create the header for you, that must be provided as the first two bytes of payload to transmit.

**Comment by mrninhvn** [comment]
Hi @jgromes ,
I would be very grateful if you have examples to accomplish that.

**Comment by jgromes** [comment]
Sorry, but full BLE support (on the protocol level) is not planned at the moment. SX128x only provides support for the physical layer.

**Comment by mrninhvn** [comment]
Hi @jgromes,
My project using SX1280 only, can I add SX128x library into arduino sketch folder and use them without `RadioLib.h` & `Module.h` or not.
I don't understand the structure of your library so you can show me how.
Thank you a lot.

**Comment by jgromes** [comment]
No, you can't do that, you always have to include RadioLib.h. SX128x.h is not a full library, only a driver for a specific module. The other radio drivers aren't used and will be optimized away during compilation.

**Comment by mrninhvn** [comment]
Hi @jgromes ,
Can I add library to arduino sketch folder without adding to arduino library folder?

**Comment by jgromes** [comment]
I'm not sure why would you want to do that - you'd probably have to modify the include paths for the compiler.
