### ISSUE TITLE
SX126X No RXDone IRQ Signal

### ISSUE THREAD

**Issue by the-drums** [jgromes/RadioLib#152]
Hi jgromes, 

First of all thank you for your library!
Recently purchased two LAMBDA62C modules with SX1262 chip. (REV2, 915MHz)
It has separate TX & RX enable pins.
DIO2 is NOT connected to RF_SW.  (From RF Solutions they stated that will be a revision of REV3).
Pins are as followed:
"
#define NSS    11                                //select pin on LoRa device
#define NRESET 12                                //reset pin on LoRa device
#define RFBUSY 17//A3                            //busy pin on LoRa device 
#define DIO1   18//A4                            //DIO1 pin on LoRa device, used for RX and TX done 
#define DIO2   19//A5                            //DIO2 pin on LoRa device, normally not used so set to -1 
#define DIO3   -1                                //DIO3 pin on LoRa device, normally not used so set to -1
#define RX_EN  15//A1  //14//A0[DAC!!}           //pin for RX enable, used on some SX126X devices, set to -1 if not used
#define TX_EN  16//A2                                //pin for TX enable, used on some SX126X devices, set to -1 if not used 
#define SW     -1                                   //SW pin on some Dorji LoRa devices, used to power antenna switch, set to -1 if not used
#define BUZZER -1                                //pin for buzzer, set to -1 if not used
"

**I'm using the exact example codes 103 for the transmitter, 104 for the receiver.**
Only difference = 915 MHz instead of 433.
All pins are connected properly and assigned to the correct functions.
(Have tried turning of : LT.setDIO2AsRfSwitchCtrl();  as it's not connected in this module, have contacted RF Solutions for this. REV2 datasheets shows no diagram, REV3 does but with DIO2 connected, I've REV2 (REV3 doesn't exist yet)).

**The good**
- Both RX & TX modules are initialized properly as per Serial messages with DEBUG functions on.
- TX example appears to works perfect, DIO1 is triggered

**Setup**
- For testing 2pcs Wire antenna standing upright specific length for 915MHz frequency.
- 2pcs Feather M0 RFM95 (AMD21G18 processor) coupled to the 2pcs LAMBDA62C (SX1262).
- (pin 8 --> = RFM95 SPI CS pin set HIGH in void(setup) to avoid SPI inteference).

**The error:**
RX example stays stuck at 
"
RXPacketL = LT.receive(RXBUFFER, RXBUFFER_SIZE, 60000, WAIT_RX)
"
No RX timeout messages as well, DIO1 is just never triggered..
Last Serial message (with debugs on) =: -> rxEnable()

- I've measured DIO1 for the TX, it's pulsing as it should.
- But RX module DIO1 stays low indefinetly, so no interrupt triggered.
- RX_EN pin is HIGH so that's working properly.

--> Things i've tried so far:
Also tried the basic RX/TX examples (but with:
if (LT.begin(NSS, NRESET, RFBUSY, DIO1, DIO2, DIO3, RX_EN, TX_EN, SW, LORA_DEVICE)) instead of the version without the TX/RX enable pins. & @ 915MHz.

--> Changing TCO voltage setting (found that one in other similar errors on this site)
No luck. 

--> Switched modules, RX for TX, TX for RX, 
no difference,  only at TX DIO1 reacts (both modules)

I also checked the command structure and the only thing i found curious is that the IRQ register is cleared after "RXDone IRQ" has been set, and the last setting hasn't got the RXDone IRQ in the IRQ register?

Working on this for 2 weeks now, hopefully somebody can help me out.

**Comment by jgromes** [comment]
Judging by the brief code snippets, I think you meant to post this issue in this repository: https://github.com/LoRaTracker/SX12XX-LoRa

RadioLib supports all SX126x devices, including LAMBDA62C - see https://github.com/jgromes/RadioLib/pull/106, so feel free to try it out.
