### ISSUE TITLE
SX1278 868Mhz Fails to initialize, because of invalid range check

### ISSUE THREAD

**Issue by lillefyr** [jgromes/RadioLib#154]
**Describe the bug**
When initializing LoRa with the frequency 868.1 MHz, radioLib returns error -12 Invalid Frequency.
This happens because of the code in RadioLib/src/modules/SX127x/SX1278.cpp
line 64 (first line in SX1278::setFrequency)
int16_t SX1278::setFrequency(float freq) {
  RADIOLIB_CHECK_RANGE(freq, 137.0, **525.0**, ERR_INVALID_FREQUENCY);

**Additional info (please complete):**
 - MCU: Wemos D1 Mini ESP8266
 - Wireless module type: SX1278 868 Mhz
 - Arduino IDE version: 1.8.512
 - Library version: 3.6.2

**Comment by jgromes** [comment]
This is intentional - SX1278 frequency range is 137 - 525 MHz, according to official documentation. See SX1276/77/78/79 datasheet, Table 1 on page 10.
