### ISSUE TITLE
Mysensors porting in this library so we can use Lora SX126X

### ISSUE THREAD

**Issue by Cloolalang** [jgromes/RadioLib#164]
**IMPORTANT: Check the wiki**
Before submitting new issue, please check the [Wiki](https://github.com/jgromes/RadioLib/wiki) and the [API documentation](https://jgromes.github.io/RadioLib/). You might find a solution to your issue there. 

**Is your feature request related to a problem? Please describe.**
Mysensors only uses RadioHead library for Lora, RadioHead does not support SX126X

**Describe the solution you'd like**
I would like to see Mysensors port in this library

**Describe alternatives you've considered**
Uart radios, but they are limited in configuration options

**Additional context**
Mysensors has its own serial tree-network protocol which is really cool, I want to keep using this transport layer but be able to use the more up-to-date Lora modules to be able to use them at narrow bandwidths (<62.5KHz) and thus be able to use them at 100% duty cycle, (conforming to the UK 433MHz ISM band regulations)

My main question, is how much work would it take to get Radiolib to carry the Mysensors serial protocol with all the features including CAD, CSMA, Automation transmission control (power control), repeater nodes, heatbeat packets etc?
P

**Comment by jgromes** [comment]
That's probably a question better directed at Mysensors devs - I'm not familiar with their system, so I can't really say if this is something that can be done easily, or if it would be beneficial to the project.

For what it's worth, RadioLib has the ability to abstract away drivers for different radio modules (via the PhysicalLayer class), so it can be used as a driver for projects that are using several different modules.
