### ISSUE TITLE
RFM22 Disable the packet handler.

### ISSUE THREAD

**Issue by QuitButton** [jgromes/RadioLib#166]
I'm hoping to be able to use this for a heating thermostat, which is FSK data that doesn't follow the sync-header-data-crc rules the packet handler in the RFM22 seems to need.

I know I can do this using the module in direct mode, but I was hoping this module might be able to do so from its FIFO if the packet handler is disabled. 

Is there a way within RadioLib to do this?

The datasheet for the RFM22 says that "When using the FIFOs, automatic packet handling may be enabled for TX mode, RX mode, or both." but I can't see what registers actually switch the packet hander off.

**Comment by jgromes** [comment]
There's currently no public API method that does this. Of course you can always enable godmode and poke around in the SPI registers directly from Arduino sketch to test stuff.

What format is the packet from the thermostat? The simplest FSK packet format that almost all sub-GHz radios in RadioLib follow is preamble-sync-data, so if it's similar to that, it should be possible.
