### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by PerrotMichel** [jgromes/RadioLib#171]
I know is not a location for questions but i have a questions with a nRF24L01 and SX126x(and other lorawan module communication familly) i can send and receive on one time a data.

Thanks mimich.

**Comment by jgromes** [comment]
I do not understand what is this question about - nRF24 or SX126x? And what exactly are you trying to achieve - some sort of duplex trasmission? Sending data between the two modules ...?

Please take the time to fill in all relevant information, as specified in the issue templates - what sort of Arduino are you using, the library version, your code, your setup ...

Closing as per the contributing doc.
