### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by PerrotMichel** [jgromes/RadioLib#172]
Hey sorry me native language was a french.

I have a simple questions with a nRF24 module, i can receive and send a data on one time with 1 module or i need 2 module for 1 receiver and 1 sender?

**Comment by jgromes** [comment]
Please don't open new issues for the same things. #171 was closed, but it's still there and can be commented on, possibly re-opened or re-labeled (once you provide the missing information).

Your question still doesn't make sense, sorry - if you want wireless communication, that implies you want to send data from place A to place B, so you need at least two modules.

If this is a question about whether you can use one nRF24 module to send data while receiving, then this is called full duplex, and no, none of the radio modules currently supported by RadioLib can do that - all of them are half-duplex by nature.
