### ISSUE TITLE
Implicit Header SX127x

### ISSUE THREAD

**Issue by juanjole** [jgromes/RadioLib#181]
Hello!

I am developing a project of LoRa based on RadioLib and I would like to know if explicit header is already supported by SX127x module because it seems it is not and only implicit header is supported. I would need this feature to implement a variable-length packet.

Thank you for all the great job!

**Comment by jgromes** [comment]
Explicit header is the default on SX127x (unless SF is set to 6, in that case implicit header is the only possible one).
Furthermore, when using SX127x in LoRa mode, variable packet length is the only supported mode of operation at this time.

So in fact, RadioLib doesn't support the inverse of what you're trying to do - implicit header and fixed-length LoRa packets. I don't think there's any particular reason why, so I will accept PRs implementing these features.

**Comment by juanjole** [comment]
That's right! I thought that because the `receive` and `readData` methods require the expected number of bytes. Is there a way to access the actual length of the received packet?

**Comment by jgromes** [comment]
Of course - see `SX127x::getPacketLength()`.

The length parameters in `receive` and `readData` methods are not required to be the number of bytes you expect to receive: if you specify more than what was actually received, you'll only get the received bytes. If you specify less, then you only get the amount of data you requested.

**Comment by juanjole** [comment]
Okay, thank you for the information!

**Comment by jgromes** [comment]
I'd rather keep this open until implicit header and fixed-length LoRa packets are implemented on SX127x - much like they are on SX126x.

**Comment by jgromes** [comment]
Implemented in the latest commit.
