### ISSUE TITLE
CC1101 version

### ISSUE THREAD

**Issue by chuyrg** [jgromes/RadioLib#183]
Recently i found that i have some cc1101 modules, i don't remember when or where i got them, long story short, they have a 0x04 version, and the library is currently hardcoded to only accept 0x14.
This thread helped me find the issue i was having since i couldn't make them start with my stm32f103.
https://e2e.ti.com/support/wireless-connectivity/other-wireless/f/667/t/370643?CC1101-VERSION-register-interpretation

**Comment by jgromes** [comment]
That's possible - when I was writing the driver for CC1101, datasheets only specified 0x14 as the version value. 0x04 will be considered valid now as well.

Thanks for reporting!
