### ISSUE TITLE
nRF905 module support

### ISSUE THREAD

**Issue by freechw** [jgromes/RadioLib#185]
This project very usefull and awesome， can you add nRF905 module support？

**Comment by jgromes** [comment]
Unfortunately I currently don't have the time to add support for nRF905 myself. However, I will accept PRs for that purpose.

**Comment by freechw** [comment]
Thanks a lot!

**Comment by jgromes** [comment]
Upon examining nRF905 datasheet, it doesn't seem that interesting - basically an nRF24 in sub-GHz frequency band. This means it's lacking a lot of features compared to the other modules supported by the library. There's also most likely no way to make it compatible with ham radio modes like RTTY or AX.25, which is a big part of RadioLib.

Unforuntately there are other priorities, so this won't be worked on.
