### ISSUE TITLE
SX1278 - setDataShaping writes into wrong register

### ISSUE THREAD

**Issue by eg321** [jgromes/RadioLib#186]
**Describe the bug**
Hi,

**setDataShaping** method for sx1278 writes into wrong register - SX127X_REG_OP_MODE, but it should use SX127X_REG_PA_RAMP (0x0A).
File to fix: \src\modules\SX127x\SX1278.cpp
Method: setDataShaping
Lines: https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX1278.cpp#L359

**Additional info:**
It seems was broken here: 
https://github.com/jgromes/RadioLib/commit/7dc7f4d76c01358ed02197b597dbd13175bd6a02

**Comment by jgromes** [comment]
You're right, that's indeed a bug that was introduced in that particular commit. Fixed, thanks for reporting!
