### ISSUE TITLE
sx1278 TCXO

### ISSUE THREAD

**Issue by kolibri86** [jgromes/RadioLib#207]
Hi,
I've added a TCXO to my HELTEC WIFI LORA 32 V2 board (sx1278+ESP32)  and i try to use this program:

```c++
#include <RadioLib.h>
#define LORA_SCK      5
#define LORA_MISO     19
#define LORA_MOSI     27
#define LORA_SS       18
#define LORA_RST      14
#define LORA_DIO0     26
#define LORA_DIO1     35
#define LORA_DIO2     34
#define FREQUENCY       434

/
SX1278 radio = new Module (LORA_SS, LORA_DIO0, LORA_RST, LORA_DIO1);


AFSKClient audio(&radio, LORA_DIO2);

void setup() {
  Serial.begin(9600);

  // initialize SX1278 with default settings
  Serial.print(F("[SX1278] Initializing ... "));
  int state = radio.beginFSK();



  if(state == ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while(true);
  }
}

void loop() {


  // 400 Hz tone
  audio.tone(400);
  delay(1000);

  // silence
  audio.noTone();
  delay(1000);


}
```

I get this error :

```
[SX1278] Initializing ... R	42	12	
Found SX127x!
R	1	8	
R	1	8	
R	1	8	
W	1	8	
R	1	8	
R	1	8	
R	1	8	
W	1	9	
R	1	8	
R	1	8	
R	1	8	
R	1	8	

address:	0x1
bits:		2 0
value:		0b1
current:	0b1000
mask:		0b111
new:		0b1001
read:		0b1000

failed, code -16
```
Can you help me solving this issue? What is the easiest way to  turn to'1' bit4 of RegTcxo (0x4b) (sx1278) ? 

THX in advance.

**Comment by jgromes** [comment]
TCXO on SX127x isn't supported by the library - as far as I know, there are no off-the-shelf SX1278/72 modules that have TCXO.

Guessing from the debug output, it seems like you'd have to set that bit before the library attemps to set the module to standby, so this would have to happen within the `beginFSK()` method, right after finding the chip. Just a guess though, the datasheet doesn't seem to specify when you need that bit.

I don't think it's a good idea to add TCXO support into the library - all the SX127x modules out there (well at least all of them that I'm aware of) have just plain XTAL, so introducing TCXO support in a similar way the SX126x driver does would probably lead to a lot of confusion. If you want to use RadioLib with your modified module, go to src/SX127x/SX127x.cpp and add something like `_mod->SPIsetRegValue(0x4B, 1, 4, 4);` before the call to `standby()` in `SX127x::beginFSK()`.
