### ISSUE TITLE
Parse the incoming byteArr from receive example

### ISSUE THREAD

**Issue by TinManAkshay** [jgromes/RadioLib#214]
Hi,

So far I have been receiving the correct data using Receiver example. Moreover, I need to parse the uint8_t* byteArr data also. Till now, I have tried lot of methods to do that, but i was unsuccessful. I have been focusing more on converting the data into char array, then using strtok() technique to parse it, but not printing anything ( no compilation error though). I wonder if its right way to parse the incoming uint8_t data. 

If anyone has already tried parsing the data received from .receive() function or any idea, please do suggest here. 

Thanks a lot,
Akshay

**Comment by jgromes** [comment]
I'm not sure what you'Re trying to achieve - `strtok()` breaks a C-string (a null-terminated char array) by some token, e.g. you can break up a sentence into words by the space character.

I guess you should start by defining what exactly you mean by "parsing". Are you trying to print the binary data as hexadecimal numbers? And what's the data you're working with?
