### ISSUE TITLE
SX1278.cpp : beginFSK doesn't initialize OOK correctly

### ISSUE THREAD

**Issue by LieBtrau** [jgromes/RadioLib#268]
Hi,

When calling beginFSK with enableOOK set to true, then line 51: "`state = setDataShaping(RADIOLIB_SHAPING_NONE);`" fails.
When enableOOK is true, then setDataShapingOOK should be used instead (I guess).

**Comment by jgromes** [comment]
You're right, SX127x shaping configuration is dependent on whether we're in FSK or OOK mode. It should be fixed now, thanks for reporting!
