### ISSUE TITLE
Is it possible to pass a member function pointer to setDioXAction?

### ISSUE THREAD

**Issue by sergimn** [jgromes/RadioLib#286]
I'm trying to develop a C++ **class** that uses RadioLib. Once I try to specify what function should be called when new data is received with `radio->setDio0Action(&this->onReceive);`, the compilation error `error: invalid use of non-static member function` appears. I've tried the following lines without success, each with a slightly different error message:
```  
radio->setDio0Action(&MyClass::onReceive);
radio->setDio0Action(MyClass::onReceive);
radio->setDio0Action(onReceive);
```

Is there a way to, when a packet is received, access the private variables of an instance? The instance has data such as nº of packets received or the node ID, something that is not compatible with making the method `static` as some people may suggest.

I found [this example](https://www.tutorialspoint.com/function-pointer-to-member-function-in-cplusplus) and this [stackoverflow answer](https://stackoverflow.com/questions/29286863/invalid-use-of-non-static-member-function) and both indicate that the underlying code has to has support for an extra parameter (the instance we want to get the data from).

In case what I'm asking needs a rework of the code, do you think it should be easy to do? I'm currently using a ESP32 with a SX127x module. Do you know if the underlying hardware supports passing a parameter to the interruption handler?

**Comment by jgromes** [comment]
The short answer is that you can't do this directly, but it's pretty easy to do indirectly.

Background: Take a look at the definition of `setDio0Action` method, e.g. in SX127x class:

```c++
    /*!
      \brief Set interrupt service routine function to call when DIO0 activates.

      \param func Pointer to interrupt service routine.
    */
    void setDio0Action(void (*func)(void));
```

You can see that the method expects the argument to be a pointer to void-type function in the global scope taking no arguments, such as

`void func(void);`

Your class method wil have a different signature however, it will be:

`void MyClass::func(void);`

That's the reason why your compilation fails in the first and fourth example. Moreover, there's a fundamental issue with examples 2 and 3: assuming `MyClass::onReceive` isn't static, you can't call it as `MyClass::onReceive()` - how would the compiler know which instance of `MyClass` to call?

Solution:

You'd have to create your own `setDio0Action()` in RadioLib, one that will have the expected signature of the `MyClass::onReceive()` method. That would of course mean exposing `MyClass` definition to RadioLib. Maybe you could do some pretty evil `void` casting to match `setDio0Action()` definition, but that doesn't seem very clean

However, there's a simpler solution - does `setDio0Action()` have to call your method directly? You can easily create a wrapper function in the global scope that would call the instance of `MyClass` you intend to call, e.g.:

```c++
MyClass mine;

void callMyClass(void) {
  mine.onReceive();
}

(...)

radio.setDio0Action(callMyClass);
```
