### ISSUE TITLE
sx1278 pin connections

### ISSUE THREAD

**Issue by hoseinaghajari** [jgromes/RadioLib#309]
Hi Im using  SX1278 Module(https://cutt.ly/zbDX8K4) and arduino uno.I Have problem with connection pins. my pins connection is this:
SCK     >> 13
MISO   >> 12
MOSI   >> 11
NSS     >> 10
RESET  >>9
DIO0   >> 2
DIO1   >> 3
and the out put is this:
**[SX1278] Initializing ... failed, code -16**

**Comment by jgromes** [comment]
You haven't posted nearly enough information - please follow the "Module not working" issue template and fill in all the details. https://github.com/jgromes/RadioLib/blob/master/.github/ISSUE_TEMPLATE/module-not-working.md

**Comment by jgromes** [comment]
Closed due to inactivity.
