### ISSUE TITLE
LLCC68 support

### ISSUE THREAD

**Issue by xixixihaha** [jgromes/RadioLib#310]
the new LLCC68 based Lora
Module is out, is it possible to add the support in the coming release?

thx

**IMPORTANT: Check the wiki**
Before submitting new issue, please check the [Wiki](https://github.com/jgromes/RadioLib/wiki) and the [API documentation](https://jgromes.github.io/RadioLib/). You might find a solution to your issue there. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jgromes** [comment]
Briefly going through the datasheet, I didn't see any significant difference between SX126x and LLCC68, so the current SX126x classes should work. Could you try it, as I don't have the LLCC68 module?

**Comment by xixixihaha** [comment]
Thanks so much. I've verified it with SX1268 code. It worked like a charm.

**Comment by jgromes** [comment]
Thanks for letting me know, I added LLCC68 as alias for SX1268, so you can use LLCC68 as any other module class:

```c++
LLCC68 radio = new Module(1, 2, 3);
```
