### ISSUE TITLE
LLCC68 SF can't be larger than 9

### ISSUE THREAD

**Issue by xixixihaha** [jgromes/RadioLib#315]
According to the spec, LLCC68 support SF5~9 @ 125K BW, SF5~10 @250K BW, SF5~11 @ 500K BW
When I was playing, I found it always failed with code -20 if SF >9 when it was doing initialization.
Looks like there are still differences between SX1268 and LLCC68.

Could you help to check?
Thanks!

**Additional info (please complete):**
 - MCU: ESP32
 - Wireless module type LLCC68
 - VScode + PlatformIO
 - Library version 4.4.2

**Comment by jgromes** [comment]
Indeed, looks like it won't be enough to just keep it as alias. I added a full class implementation for LLCC68, so now it should check bandwidth and spreading factor properly.

**Comment by jgromes** [comment]
@mrx23dot I would suggest seaching the datasheet again: it does say which combinations are valid:

![Screenshot_96](https://github.com/jgromes/RadioLib/assets/3407192/d90094b8-e477-4122-b78f-91676920cde1)
