### ISSUE TITLE
packetFrequencyError for SX126x

### ISSUE THREAD

**Issue by tshcherban** [jgromes/RadioLib#318]
Im wondering if packetFrequencyError can be obtained somehow? Currently im experimenting with LoRa and found out that Arduino Lora lib has this method to determine difference between frequencies of two radios, so i can adjust one of them.

**Comment by jgromes** [comment]
This is not implemented at the moment, the official SX126x documentation says nothing on the subject. Apparently the module can do it, it's just not documented.

**Comment by tshcherban** [comment]
Haven't found corresponding registers in a register map. Maybe it is not implemented (and necessary) in SX126x due to using TXCO.
