### ISSUE TITLE
Two way communication

### ISSUE THREAD

**Issue by prerak9** [jgromes/RadioLib#325]
Hello, 
I have successfully tested the receive and transmit example codes with SX1278 and arduino. I got it working perfectly. Now, I want to have two way communication where receiver can also send feed back to transmitter i.e. I am not able to find any relevant example code for my purpose so, i want you to please help me with a sample code to accomplish this.

Two way communication means that two devices can work as both receiver as well as transmitter. Hope you understood my doubt.

Thank You

**Comment by jgromes** [comment]
Did you mean to post this in https://github.com/jgromes/RadioLib/discussions/324?

Closing as duplicate.
