### ISSUE TITLE
MKR 1310 Chip Not Found

### ISSUE THREAD

**Issue by engeen-nl** [jgromes/RadioLib#344]
### Discussed in https://github.com/jgromes/RadioLib/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **engeen-nl** August  2, 2021</sup>
I'm attempting to use the on-board SX1276 on the MKR1310 for FSK modulation. When I try the SX127x_FSK_Modem example I'm getting a
`[SX1276] Initiating ... failed, code -2`
-2 means ERR_CHIP_NOT_FOUND
I'm sure using the right modem (SX1276 address 0x12) and it is wired, because when I use sandeepmistry's library I can communicate between arduino's using LoRa modulation.
Selected pins:
`SX1276 radio = new Module(LORA_IRQ_DUMB, LORA_IRA, LORA_RESET, RADIOLIB__NC, SPI1);`
I also tried LORA_BOOT0 but no succes. I also tried the reset mechanism as used by the LoRa library of sandeepmistry, but this also doesn't work. Anyone any ideas? Help would be greatly appreciated.</div>

**Comment by jgromes** [comment]
Closing for now as a duplicate discussion exists.
