### ISSUE TITLE
Non-blocking morse implementation.

### ISSUE THREAD

**Issue by rnbokade** [jgromes/RadioLib#36]
We are trying to use task scheduler in our application. However, the blocking functions like delay() and tone() cause problems in timing. Can the morse protocol be remade using millis or some other non-blocking function?

**Comment by jgromes** [comment]
> Can the morse protocol be remade (...)

Absolutely. Unforunately, I don't have the time work on it right now, but I will happily accept PRs for this.

**Comment by jgromes** [comment]
Hey, is this still relevant? If so, I have a bit more time now, so I could have a look at it.

**Comment by rnbokade** [comment]
That would be great.

**Comment by jgromes** [comment]
OK, what sort of API do you have in mind? Whatever we come up with must be compatible with the current interface.

**Comment by jgromes** [comment]
Closed due to inactivity, feel free to reopen later.

**Comment by rnbokade** [comment]
begin (float base, uint8_t speed=20. bool non_blocking=false) should work as a goo API I guess

**Comment by jgromes** [comment]
I was talking more about the `print` functions. "Non-blocking" suggests you would want to do other things while Morse data is being sent. Regardless of whether waiting is implemented via `delay` or `millis`, as long as there's a loop that does nothing but wait, it is a blocking function.

**Comment by rnbokade** [comment]
Right.... Will think about it more.
