### ISSUE TITLE
RP2040 - Raspbery pi pico support

### ISSUE THREAD

**Issue by karaketir16** [jgromes/RadioLib#361]
There is no support for Raspberry pi pico arduino framework. If no one else does it, I'll try to port it.

**Comment by jgromes** [comment]
Seeing as I don't have the board to test, feel free to add support! Assuming no major differences in the framework, it should be as easy as adding all the definitions in BuildOpt.h

**Comment by jgromes** [comment]
Added support in the latest commit, but keep in mind it is untested as I don't have the hardware.

**Comment by karaketir16** [comment]
I'll let you know if I test it.
