### ISSUE TITLE
Use custom spi pins other than default on arduino mega

### ISSUE THREAD

**Issue by anandspathak** [jgromes/RadioLib#381]
How can I use custom spi pins on mega instead of default ones as these are occupied by lcd screen? Have no idea,
Regards
Anand Pathak
India

**Comment by jgromes** [comment]
If you're referring to Arduino Mega, that only has one SPI bus and cannot change where its pins are located. You can try a software-emulated SPI (e.g. https://github.com/MajenkoLibraries/SoftSPI), then provide that to the constructor, something along the lines of:

```c++
SoftSPI mySPI(miso, mosi, sck);
SX1278 radio = new Module(cs, dio0, rst, dio1, mySPI);
```

Also: This is not an issue - converting to discussion.

Also also: Please don't open issues for things that are not ... well ... issues. That's what discussions are for.
