### ISSUE TITLE
[SX1278] Can't receive long packets in FSK mode

### ISSUE THREAD

**Issue by notsleep196** [jgromes/RadioLib#399]
Hello!

We are trying to use your lib to receive long packets (more than 64 bytes) in FSK mode . Yes, we know that SX127x have only 64 bytes of FIFO in FSK mode, but it can receive long packets with some special workflow (paragraph 2.1.13.5 in datasheet).
Unfortunately Radiolib does not support such workflow and packets more than 64 bytes in FSK for SX127x. We've found several incompatibilities described below.

Goal of this issue is to describe these incompatibilities and discuss possible solutions. Maybe we'll implement some changes at application side, other at Radiolib with your assistance. In worst scenario we'll fork Radiolib with our rough patches.

General scheme to work with long packets is to use FIFOLevel interrupt, and start reading FIFO until it's fully filled:
 - Start reading bytes from the FIFO when FifoEmpty is cleared or FifoThreshold becomes set.
 - Suspend reading from the FIFO if FifoEmpty fires before all bytes of the message have been read.
 - Continue to step 1 until PayloadReady or CrcOk fires
 - Read all remaining bytes from the FIFO either in Rx or Sleep/Standby mode
 - FIFOLevel interrupt is maped to DIO1 by default, so we can use setDio1Action() function to connect FIFOThreshold handler with this interrupt.

Example of FIFOThress handler:
```cpp
void IRAM_ATTR onFIFOThresh() {
    std::vector<uint8_t> dataVector;
    while ((radio->getIRQFlags() >> 14) & 0b01) == 0) {  //check FIFOEmpty irq flag
        uint8_t buffer[16];  //FIFO_THRESHOLD + 1 bytes
        int state = norbyTransceiver.readData(buffer, 16);
        if (state == ERR_NONE) {
            dataVector.insert(dataVector.end(), buffer, buffer + 16);
        }
    }
}
```
And it doesn't work properly now. We've found several issues here:

1. readData() method puts module to standby mode, so it can't receive anything after FIFOLevel interrupt was triggered on DIO1 and onFIFOThresh() irq handler called. So we can receive FIFO_THRESHOLD of bytes only.

2. Strange part with length variable for FSK mode. I think clearFIFO() function will never be called in FSK mode, because in string 542 in SX127x.cpp we can see
```cpp
length = getPacketLength();
```
and
```cpp
size_t packetLength = getPacketLength();
if(packetLength > length) {
    clearFIFO(packetLength - length);
}
```
after it. I think its not valid way for long packets

3. readData() method calls clearIRQFlags() and thereby sets all irq flags to 1, FIFOEmpty flag goes to 1 also, but FIFO yet not empty actually.

4. fixedPacketLengthMode(255) can't set packet length more than 64 bytes now (limited to SX127X_MAX_PACKET_LENGTH_FSK = 64 bytes).

We've proved this concept by rough changes in Radiolib and received long packets at SX1278, but these changes is not ready to be merged in main repo. So, your assistance is really appreciated here.

MCU: ESP8266
Wireless module type SX1278
Library version 4.6.0

**Comment by jgromes** [comment]
What you're decribing is basically the stream mode from #201

To answer your question, yes, it is possible and would be a welcome change since 64 bytes is quite limiting. Furthermore, if we're clever about the implementation, it could be done generically for more than just SX127x.

Technically, there's a workaround for this, you can use direct mode reception and receive any packet, but it's not nearly as convenient.

So yeah, this is on my massive TODO list, if you guys have something that implements this we can seeif we can make it a bit more generic to support other modules as well.

I propose to close this (since it's technically a duplicate) and move the conversation to #201.
