### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by acontini** [jgromes/RadioLib#40]
Will RadioLib support ESP32 in the near future?

**Comment by jgromes** [comment]
As a platform (running RadioLib on ESP32) or as a module (using ESP32 as a WiFi module for some other microcontroller)?

If it's the former, see #39. If it's the latter, I'm not sure - does ESP32 have some sort of AT firmware (like ESP8266)?

**Comment by jgromes** [comment]
Support for ESP32 platform was added in update 1.4.0, support for ESP32 as module is not planned at the time.
