### ISSUE TITLE
Problem AFSK SX1278

### ISSUE THREAD

**Issue by jp-polito** [jgromes/RadioLib#411]
Hi! I'm trying to run the AFSK example in my SX1278 module it works but I can't decode the signal. It seems the module is active all the time. I can't understand what's going on.
![Captura de tela de 2021-11-25 12-57-07](https://user-images.githubusercontent.com/93289692/143472731-ad4daf25-0cad-4170-9d4f-8a9af4202a95.png)

**Comment by jgromes** [comment]
> I can't understand what's going on

Neither can I if you don't tell me what are you using to decode. Soundmodem should work, but I think that's Windows-only.

**Comment by jp-polito** [comment]
II'm trying to use GQRX's own decoder.

**Comment by jp-polito** [comment]
Is it normal for the module to be activated all the time? I'm sending some prints.
![Captura de tela de 2021-11-25 14-15-06](https://user-images.githubusercontent.com/93289692/143481601-25eeda5a-34bc-4ea2-aafe-76ba665834a8.png)
![Captura de tela de 2021-11-25 14-15-30](https://user-images.githubusercontent.com/93289692/143481604-f9608ef8-65e1-4bb7-a3b8-f5954b9c690c.png)

**Comment by jgromes** [comment]
> Is it normal for the module to be activated all the time

No, that shouldn't happen - I pushed a commit which should fix that.

> I'm trying to use GQRX's own decoder.

OK, do you know how it works? Because I was never able to get it to work with known good AX.25 frames.

**Comment by jp-polito** [comment]
I've already run some tests using gqrx and AFSK on other circuits and it worked. And about the carrier I used a logic level converter from 5V to 3.3V

**Comment by jgromes** [comment]
I tried this in a VM running Ubuntu 18.04 and wasn't able to replicate the issue using Arduino Uno and SX1278.

![Screenshot_18](https://user-images.githubusercontent.com/3407192/143689283-cf2055fa-cf8a-4a0b-bc90-ff07b9a54ac0.png)

Pretty much default settings, just changed mode to NFM and adjusted filter width.
