### ISSUE TITLE
Morse code using OOK

### ISSUE THREAD

**Issue by jgromes** [jgromes/RadioLib#452]
### Discussed in https://github.com/jgromes/RadioLib/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **Sumya99** January 22, 2022</sup>
Hello sir, 

First, I am a quite novice in this RF field and hope you help me. I am trying to transmit Morse code using OOK modulation scheme on RFM95PW. Is it possible using this library? 

Thanks in advance</div>

**Comment by jgromes** [comment]
@Sumya99 turns out there was an issue when OOK was enabled **before** starting AFSK. 

It should be fixed now, I tried it with SDR and can clearly hear 400 Hz tones in AM mode.

**Comment by Sumya99** [comment]
Thanks! Yes it works :))))
