### ISSUE TITLE
Data packet limited artificially to 254 on SX127x

### ISSUE THREAD

**Issue by nseidle** [jgromes/RadioLib#455]
This is a tiny issue but I hit it so I suspect others are as well.

**Bug:**
* [Line 451](https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX127x.cpp#L451) limits packet length to 254 went the max limit is 255. Should be `len > RADIOLIB_SX127X_MAX_PACKET_LENGTH` unless I'm missing something else.
* I've tested and a 255 byte char[] transmits/receives just fine.
* Additionally, the examples are a bit misleading "// you can also transmit byte array up to 256 bytes long". Does 'up to' include or or exclude 256 bytes? I'd say something like "// you can also transmit arrays 255 bytes or smaller" just to make it crystal clear.

I can submit a PR if you agree. This looks like a typo/bug as the other SX12#x.cpp files are all `len > RADIOLIB_SX12#X_MAX_PACKET_LENGTH`.

![image](https://user-images.githubusercontent.com/117102/151057214-ea8b2407-9636-4db8-a5a1-8c1557e53727.png)

![image](https://user-images.githubusercontent.com/117102/151057845-23522e73-c4c3-4199-afdc-f1c2fde6ed4d.png)

**Comment by jgromes** [comment]
This probably remained from a previous version of the library. Fxied by merging #457.
