### ISSUE TITLE
EByte E220-900T22D UART module support

### ISSUE THREAD

**Issue by ArmanYvz** [jgromes/RadioLib#467]
Hello, I have EByte E220-900T22D module connected to Arduino Uno. Link to module: https://www.ebyte.com/en/product-view-news.html?id=1212

I'm searching for a library to control my module. I will build a packet network that supports audio and scalar data transmission for emergency situations. I bought 4 pieces of E220-900T22D modules, these modules use LLCC68 as an integrated circuit, and i though i can control it using your library, as LLCC68 is supported, but i had hard time introducing module to RadioLib library.

The module is UART, so I don't know if I can use RadioLib library with this module. I couldn't define constructor, because it waits for 4 parameters, and unlike your tutorial which says that a module can be constructed as Module(Tx, Rx), it isn't possible. Library awaits for SPI pin inputs. Even if i only input Rx and Tx, and leave other params as null string, i'm taking the error "[LLCC68] Initializing ... failed, code -2"

All my connections between arduino and lora module are correct, because i tried connection with another library and it was successful. But i want to use your library because it has more features and it seems more stable.

Can i use my module along with RadioLib? If yes, how should I define constructor for UART? Can you help me?

**Comment by jgromes** [comment]
Unfortunately those modules are not supported - RadioLib requires direct access to the transciver chip (LLCC68 in this case). In your module, there's an additional MCU in that path, which provides the UART interface.

The references to UART were from a previous version of the library (<5.0.0), before UART support was dropped. I removed the outdated references, thanks for letting me know.
