### ISSUE TITLE
Useless `fabs` call?

### ISSUE THREAD

**Issue by loopj** [jgromes/RadioLib#490]
I'm guessing the intention here is for this to be `fabs((rxBw * 1000.0) - point) <= 1000)`

https://github.com/jgromes/RadioLib/blob/2e7067de8101bcbebfca696016271481d10d7712/src/modules/CC1101/CC1101.cpp#L490

**Comment by jgromes** [comment]
You're right, that was indeed incorrect. Should be fixed now, thanks for reporting!
