### ISSUE TITLE
SX127x::setMode(uint8_t mode)    实际输出信号会冗余

### ISSUE THREAD

**Issue by heliang1795** [jgromes/RadioLib#509]
int16_t SX127x::setMode(uint8_t mode) {
  uint8_t checkMask = 0xFF; //获取当前工作模式,在 FSK RX 模式下禁用对 RX 位的检查，因为它有时似乎失败了 (#276)
  if((getActiveModem() == RADIOLIB_SX127X_FSK_OOK) && (mode == RADIOLIB_SX127X_RX)) {
    // disable checking of RX bit in FSK RX mode, as it sometimes seem to fail (#276)
    checkMask = 0xFE;
  }//重新设置模式 设为待机模式
  return(_mod->SPIsetRegValue(RADIOLIB_SX127X_REG_OP_MODE, mode, 2, 0, 5, checkMask));
}
这个函数 在执行时 ,通过在SPI线路上的观测,发现 会有先有2次读取状态寄存器 ,然后再写入寄存器,然后再读取2次寄存器,
明显降低了效率,出现了冗余.

**Comment by jgromes** [comment]
Please use English in issues.
