### ISSUE TITLE
Transmit.ino is not Working for ESP8266

### ISSUE THREAD

**Issue by UdayChaduvula** [jgromes/RadioLib#528]
When I upload the example code to the ESP8266 module. In the serial monitor I observed the continous wdt_reset printing in the serial monitor. whereas the same code is working for ESP32

Module Used:

1. ESP8266

Coding Platform
1. Arduino IDE

**Comment by jgromes** [comment]
Please provide the information listed in the [Module not working](https://github.com/jgromes/RadioLib/blob/master/.github/ISSUE_TEMPLATE/module-not-working.md) template.

**Comment by jgromes** [comment]
Closing as inactive.
