### ISSUE TITLE
Does not act setRfSwitchState

### ISSUE THREAD

**Issue by Jubamo** [jgromes/RadioLib#531]
In the (https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX127x.cpp), line 405, if the IF is true, setRfSwitchState is not executed.

**Comment by jgromes** [comment]
Here's the relevant section:

https://github.com/jgromes/RadioLib/blob/3df3b092ebf412bd0b26524e7b296733bd6a62f7/src/modules/SX127x/SX127x.cpp#L405-L411

You're right, if continuous mode is used the RF switch will not be actuated. Fixed now, thanks for reporting!
