### ISSUE TITLE
Sx1262 connected to rp2040 SPI1

### ISSUE THREAD

**Issue by 01Space** [jgromes/RadioLib#537]
Hi，
I want to use SPI1 of rp2040 to control sx1262 module
RP2040-GPIO11 MOSI
RP2040-GPIO12 M1SO
RP2040-GPIO14 SCK
How can I modify the code to make the sx262 module work properly?
thank you!

**Comment by jgromes** [comment]
By default, RadioLib uses the SPI as defined by Arduino. See [this wiki page](https://github.com/jgromes/RadioLib/wiki/Basics#non-standard-spi-setup) for information about non-standard SPI setups.

**Comment by 01Space** [comment]
thank you!！It doesn't work on rp2040. I plan to change it to spi0 to solve this problem

**Comment by jgromes** [comment]
Closed due to inactivity.
