### ISSUE TITLE
Bad offset in setRSSIConfig

### ISSUE THREAD

**Issue by F6GNJ** [jgromes/RadioLib#538]
Hello,
In RadioLib @ 5.2.0, i use the getRSSI() function which is very useful for cheaply measuring an RF signal. The measurement is excellent in precision and linearity in the range -110 to -40 dBm with an accuracy of 0.5dB. I decided to use setRSSIConfig to average and above all compensate the value read in the event of a loss in coax or a gain in an LNA. The variation from -16 to +15 dB only changes the value read by + or - 1.5dB, strange like a bad shifted value ? 

In SX127x.cpp -> int16_t SX127x::setRSSIConfig(uint8_t smoothingSamples, int8_t offset)

I modified:

state = _mod->SPIsetRegValue(RADIOLIB_SX127X_REG_RSSI_CONFIG, offset, 7, 3);
by
state = _mod->SPIsetRegValue(RADIOLIB_SX127X_REG_RSSI_CONFIG, offset<<3, 7, 3);

And the range is now really -16 to +15 dB

I hope this will be useful?

@jgromes, Thank you for the work of this very useful library !

Arnaud.

**Comment by jgromes** [comment]
Fixed in [ba67ce2](https://github.com/jgromes/RadioLib/commit/ba67ce2720d7809ff52bc3d58d61613a46481592) - thanks for reporting!

Also, feel free to open a pull request if (or rather when) you spot and also fix a bug ;)

**Comment by F6GNJ** [comment]
Of course, with pleasure, I admit that I don't know the procedures very well, but I will learn :-)
Best wishes
Arnaud.
