### ISSUE TITLE
Ebyte e22 400M-30S with Sx1268 working with ESP8266. NOT Communicating

### ISSUE THREAD

**Issue by Upergy** [jgromes/RadioLib#539]
**IMPORTANT: Before submitting an issue, please check the following:**
1. **Read [CONTRIBUTING.md](https://github.com/jgromes/RadioLib/blob/master/CONTRIBUTING.md)!** Issues that do not follow this document will be closed/locked/deleted/ignored.
2. RadioLib has a [Wiki](https://github.com/jgromes/RadioLib/wiki) and an extensive [API documentation](https://jgromes.github.io/RadioLib/). You might find a solution to your issue there.
3. Make sure you're using the latest release of the library! Releases can be found [here](https://github.com/jgromes/RadioLib/releases).
4. Use [Arduino forums](https://forum.arduino.cc/) to ask generic questions about wireless modules, wiring, usage, etc. Only create issues for problems specific to RadioLib!
5. Error codes, their meaning and how to fix them can be found on [this page](https://jgromes.github.io/RadioLib/group__status__codes.html).

I try to communicate with 2 E22 400M30S both connected to esp8266. One Transmitting and one Receivig.(see the hardware setup below).

But I receive no DATA : 
 

TRANSMIT SKETCH------------------------------------------------------------------------------------------------------------------------------

```c++
// include the library
#include <Arduino.h>

#include <RadioLib.h>
#include <SPI.h>
// Forward declaration of functions

void enableTX(void);

// GPIOs to control E22 RX_EN and TX_EN
#define RADIO_RXEN 16
#define RADIO_TXEN 2

// SX1262 module = eByte E22 module
SX1268 radio = new Module(15, 4, 4, 5);
// 5 = NSS, 4 = DIO1  4 = DIO2 (not connected), 5 is BUSY

void setup() {
  
  //pinMode(1,FUNCTION_3);
//pinMode(3,FUNCTION_3);
  Serial.begin(115200);

  SPI.begin();
  // SCLK GPIO 18, MISO GPIO 19, MOSI GPIO 23, CS == NSS GPIO 5
  
  Serial.print(F("[SX1262] Initializing ... "));

  // initialize SX1262 
  // carrier frequency:           868.0 MHz
  // bandwidth:                   125.0 kHz
  // spreading factor:            7
  // coding rate:                 5
  // sync word:                   0x1424 (private network)
  // output power:                22 dBm
  // current limit:               60 mA
  // preamble length:             8 symbols
  // CRC:                         enabled
 int state = radio.begin(434.0, 125.0, 9, 7, 0x12, 12, 8, 1.6, false);

  if (state == RADIOLIB_ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }



  //Important! To enable transmit you need to switch the SX126x antenna switch to TRANSMIT
   enableTX(); 
}

void loop() {
//TRANSMIT
    Serial.print(F("[SX1268] Transmitting packet ... ")); 

  // you can transmit C-string or Arduino string up to
  // 256 characters long
  // NOTE: transmit() is a blocking method!
  //       See example SX126x_Transmit_Interrupt for details
  //       on non-blocking transmission method.
 String str = "Hello World!";
  int state = radio.transmit(str);
  
  // you can also transmit byte array up to 256 bytes long
  /*
    byte byteArr[] = {0x01, 0x23, 0x45, 0x56, 0x78, 0xAB, 0xCD, 0xEF};
    int state = radio.transmit(byteArr, 8);
  */
  if (state == RADIOLIB_ERR_NONE) {
    // the packet was successfully transmitted
    Serial.println(F("success!/t/t"));
    Serial.println(str);
    // print measured data rate
    Serial.print(F("[SX1268] Datarate:\t"));
    Serial.print(radio.getDataRate());
    Serial.println(F(" bps"));

  } else if (state == RADIOLIB_ERR_PACKET_TOO_LONG) {
    // the supplied packet was longer than 256 bytes
    Serial.println(F("too long!"));

  } else if (state == RADIOLIB_ERR_TX_TIMEOUT) {
    // timeout occured while transmitting packet
    Serial.println(F("timeout!"));

  } else {
    // some other error occurred
    Serial.print(F("failed, code "));
    Serial.println(state);

  }

  // wait for a second before transmitting again
  delay(1000);
}






// Set TX pin HIGH and RX pin LOW to switch to TRANSMIT
void enableTX(void)
{
  digitalWrite(RADIO_RXEN, LOW);
  digitalWrite(RADIO_TXEN, HIGH);
  delay(100);
}

```

---------------------------------------------------------------------------------------------------------------------------------------------------

RECEIVE SKETCH --------------------------------------------------------------------------------------------------------------------------------

```c++
  /*
   RadioLib SX126x Receive Example

   This example listens for LoRa transmissions using SX126x Lora modules.
   To successfully receive data, the following settings have to be the same
   on both transmitter and receiver:
    - carrier frequency
    - bandwidth
    - spreading factor
    - coding rate
    - sync word
    - preamble length

   Other modules from SX126x family can also be used.

   For full API reference, see the GitHub Pages
   https://jgromes.github.io/RadioLib/
*/

// include the library
#include <Arduino.h>

#include <RadioLib.h>
#include <SPI.h>
// Forward declaration of functions
void enableRX(void);


// GPIOs to control E22 RX_EN and TX_EN
#define RADIO_RXEN 16
#define RADIO_TXEN 2

// SX1268 module = eByte E22-400M30S module
SX1268 radio = new Module(15, 4, 4, 5);
// 5 = NSS, 4 = DIO1  4 = DIO2 (not connected), 5 is BUSY

void setup() {
  //pinMode(1,FUNCTION_3);
//pinMode(3,FUNCTION_3);
  Serial.begin(115200);

  SPI.begin();
  // SCLK GPIO 18, MISO GPIO 19, MOSI GPIO 23, CS == NSS GPIO 5
  
  Serial.print(F("[SX1268] Initializing ... "));

  // initialize SX1268 
  // carrier frequency:           434.0 MHz
  // bandwidth:                   125.0 kHz
  // spreading factor:            9
  // coding rate:                 7
  // sync word:                   0x34
  // output power:                10 dBm
  // current limit:               8 mA
  // preamble length:             8 symbols
  // CRC:                         enabled
 int state = radio.begin(434.0, 125.0, 9, 7, 0x12, 10, 8, 1.6, false);

  if (state == RADIOLIB_ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }

  

  // Important! To enable receive you need to switch the SX126x antenna switch to RECEIVE 
  enableRX();


}

void loop() {
  
  
  Serial.print(F("[SX1268] Waiting for incoming transmission ... "));

  // you can receive data as an Arduino String
  // NOTE: receive() is a blocking method!
  //       See example ReceiveInterrupt for details
  //       on non-blocking reception method.
  String str="Helloe";
  int state = radio.receive(str,0);

  // you can also receive data as byte array
  /*
    byte byteArr[8];
    int state = lora.receive(byteArr, 8);
  
*/
  if (state == RADIOLIB_ERR_NONE) {
    // packet was successfully received
    Serial.println(F("success!"));

    // print the data of the packet
    Serial.print(F("[SX1262] Data:\t\t"));
    Serial.println(str);

    // print the RSSI (Received Signal Strength Indicator)
    // of the last received packet
    Serial.print(F("[SX1262] RSSI:\t\t"));
    Serial.print(radio.getRSSI());
    Serial.println(F(" dBm"));

    // print the SNR (Signal-to-Noise Ratio)
    // of the last received packet
    Serial.print(F("[SX1262] SNR:\t\t"));
    Serial.print(radio.getSNR());
    Serial.println(F(" dBm"));

  } else if (state == RADIOLIB_ERR_RX_TIMEOUT) {
    // timeout occurred while waiting for a packet
    Serial.println(F("timeout!"));

  } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
    // packet was received, but is malformed
    Serial.println(F("CRC error!"));

  } else {
    // some other error occurred
    Serial.print(F("failed, code "));
    Serial.println(state);

  }
  // wait for a second before transmitting again
  delay(1000);
}




  // Set RX pin HIGH and TX pin LOW to switch to RECEIVE
void enableRX(void)
{
  digitalWrite(RADIO_RXEN, HIGH);
  digitalWrite(RADIO_TXEN, LOW);
  delay(100);
}
```
-------------------------------------------------------------------------------------------------------------------------------------------------
![moniteur série RX](https://user-images.githubusercontent.com/107033485/173854112-2b173323-4a3b-48fa-9676-119c045237c2.png)
![moniteur serie TX](https://user-images.githubusercontent.com/107033485/173854121-f728d4f4-6ae6-4372-b3c0-3aa1198583b5.png)

**Hardware setup**
![Capture d’écran 2022-06-10 152704](https://user-images.githubusercontent.com/107033485/173849815-f2618dd8-2064-43ca-9f48-f3d2c1449ec3.png)

**Debug mode output**
Enable all [debug levels](https://github.com/jgromes/RadioLib/wiki/Debug-mode) and paste the Serial monitor output here.

**Additional info (please complete):**
 - MCU: [ESP8266 ]
 - Link to Arduino core: []
 - Wireless module type [SX1268]
 - Arduino IDE version  [e.g. 1.8.5]
 - Library version [e.g. 3.0.0]

**Comment by jgromes** [comment]
Here's just a few things that I think are wrong in your code and wiring:

1. I have no idea how you arrived at the conclusion that `Module(15, 4, 4, 5);` is the right way to go. Based on the schematic, I would say `Module(15, 4, RADIOLIB_NC, 5);` is correct - assuming "CS" on your ESP8266 is actually GPIO15.

2. Why are you connecting RST of your ESP8266 to the NRST of the E22 module? That's just connecting reset input to another reset input - best case, nothing happens, worst case, the resets try to trigger each other.

3. You're calling `SPI.begin();`. Why? The library does that internally, unless you explicitly tell it not to - which you did not.

4. You don't have to manually set the RF switch. From the examples:

```c++
  // some modules have an external RF switch
  // controlled via two pins (RX enable, TX enable)
  // to enable automatic control of the switch,
  // call the following method
  // RX enable:   4
  // TX enable:   5
  /*
    radio.setRfSwitchPins(4, 5);
  */
  ````
  
  5. This:
  
  ```c++
  String str="Helloe";
  int state = radio.receive(str,0);
  ```
  
Why are you setting the string that you want to receive into? And why are you setting the second argument to 0? That will tell the library to receive 0 bytes. Which it actually seems to be doing - but then again, judging by the 96 Mbps bit rate (as reported by the transmit sketch) you have achieved, I don't think anything is actually being sent.

**Comment by Upergy** [comment]
Hello,

I just wanted to let u know that it’s working !

Thanks for your precious help 😊

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Jan ***@***.***>
Envoyé le :mercredi 15 juin 2022 19:28
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [jgromes/RadioLib] Ebyte e22 400M-30S with Sx1268 working with ESP8266. NOT Communicating (Issue #539)


Here's just a few things that I think are wrong in your code and wiring:

  1.  I have no idea how you arrived at the conclusion that Module(15, 4, 4, 5); is the right way to go. Based on the schematic, I would say Module(15, 4, RADIOLIB_NC, 5); is correct - assuming "CS" on your ESP8266 is actually GPIO15.
  2.  Why are you connecting RST of your ESP8266 to the NRST of the E22 module? That's just connecting reset input to another reset input - best case, nothing happens, worst case, the resets try to trigger each other.
  3.  You're calling SPI.begin();. Why? The library does that internally, unless you explicitly tell it not to - which you did not.
  4.  You don't have to manually set the RF switch. From the examples:

  // some modules have an external RF switch

  // controlled via two pins (RX enable, TX enable)

  // to enable automatic control of the switch,

  // call the following method

  // RX enable:   4

  // TX enable:   5

  /*

    radio.setRfSwitchPins(4, 5);

  */

  1.  This:

String str="Helloe";

int state = radio.receive(str,0);

Why are you setting the string that you want to receive into? And why are you setting the second argument to 0? That will tell the library to receive 0 bytes. Which it actually seems to be doing - but then again, judging by the 96 Mbps bit rate (as reported by the transmit sketch) you have achieved, I don't think anything is actually being sent.
