### ISSUE TITLE
Getting -705 when begin()

### ISSUE THREAD

**Issue by GilbertLau** [jgromes/RadioLib#551]
I am trying to init LORA on a TTGO T-Beam ESP32 LORA.   However, I keep getting -705.   Is there something I am missing?   Thanks for your help in advance.

#define SCK           5   // GPIO5  -- SX1278's SCK
#define MISO         19   // GPIO19 -- SX1278's MISnO
#define MOSI         27   // GPIO27 -- SX1278's MOSI
#define SS           18   // GPIO18 -- SX1278's CS
#define RST          23   // GPIO14 -- SX1278's RESET
#define RADIO_DIO1_PIN              33
#define BUSY_PIN     32

SPIClass newSPI(VSPI);
SX1268 radio = new Module(SS, RADIO_DIO1_PIN, RST, BUSY_PIN, newSPI);

newSPI.begin(SCK, MISO, MOSI, SS);
int state = radio.begin(433.0F);

**Hardware setup**
LILYGO® TTGO T-Beam V1.1 ESP32 LORA

**Debug mode output**
M       SX126x
CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

CMD     80
DATW    0       0

**Comment by jgromes** [comment]
Based on the debug output, the SPI is always returning 0x00 - that probably means there's an issue with the hardware. I would check if the pins are actually correct.

**Comment by jgromes** [comment]
Closed due to inactivity.
