### ISSUE TITLE
LoRa Airtime Calculation: getTimeOnAir Vs  LoRaTools Air time calculator

### ISSUE THREAD

**Issue by Mostafa-ashraf19** [jgromes/RadioLib#570]
**Describe the bug**
I think there is an error in calculations of [getTimeOnAir](https://jgromes.github.io/RadioLib/class_s_x126x.html#a7e342ddbef84cf845bef8f4448b8da10) method.

**Expected behavior**
I used [LoRaTools Air time calculator](https://loratools.nl/#/airtime), with these settings:
- SF = 7
- BW = 125
- CR = 3 -> 4/7
- Payload = 127 bytes
- Preamble length = 8 symbols
I got Time on air from [LoRaTools Air time calculator](https://loratools.nl/#/airtime) = 285.95 Millisecond, but the result coming from getTimeOnAir method is = 914432 Microseconds so 914.432 Millisecond.

Are those calculations from the getTimeOnAir method, right?

**Comment by jgromes** [comment]
Closed due to inactivity.
