### ISSUE TITLE
PAN3031 support

### ISSUE THREAD

**Issue by garudaonekh** [jgromes/RadioLib#604]
Hi,
PAN3031 is just released https://www.iot-rf.com/LoRa-Module-dc17786.html. It's cheaper than LLCC68 about 20% to 30% depending on where you buy it. It has good range as per its document. I can't get it work on Arduino platform. There're however sample code for STM32.

https://github.com/vacabun/PAN3031_demo

Thanks;

**Comment by jgromes** [comment]
It's not entirely clear to me what exactly is this module - some SX127x/6x from an alternative suppliers (such as the RFM9x moduels, which are basically just SX127x silicon in a differently labeled package)?

The documentation seems very lacking, and the STM32 project doesn't really clarify much either. So unless the module becomes widespread and sufficiently detailed documentation is provided, I don't see its support in RadioLib as viable.
