### ISSUE TITLE
LoRa RA-02 with TTGO Eth PoE always exits with code -2 in Arduino

### ISSUE THREAD

**Issue by LoRaMaxe** [jgromes/RadioLib#621]
I am using the
https://www.tindie.com/products/lora-aprs/lora-on-poe-esp32-board/
with the
https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE
but all my tries with Arduino are exiting with code -2.
But it is working with
https://github.com/lora-aprs/LoRa_APRS_iGate

I assume that the SPI isn't working properly.

**Comment by jgromes** [comment]
This is missing almost all information I need to hlpe you.

Please follow the appropriate issue template: https://github.com/jgromes/RadioLib/blob/master/.github/ISSUE_TEMPLATE/module-not-working.md

**Comment by jgromes** [comment]
Closed due to inactivity.
