### ISSUE TITLE
Enable GFSK on SI4432

### ISSUE THREAD

**Issue by Dantali0n** [jgromes/RadioLib#625]
**Is your feature request related to a problem? Please describe.**
The GFSK feature in the SI4432 is present all be it poorly documented. It has a fixed BT of 0.5 hence you can't find how to configure it from the documentation. But having to manually set the registers to configure it is a bit tedious.

**Describe the solution you'd like**
Expose regular methods and parameters to enable GFSK as opposed to FSK with similar interfaces as newer chips supported by RadioLib.

**Describe alternatives you've considered**
Manually setting the registers

**Additional context**
The GFSK shaper does not work in directmode so ideally the methods exposed by RadioLIB should account for this, potentially disabling GFSK in direct mode as it leads to undefined behavior or it might outright return an error. If so this error should be caught and exposed.

All I had to do to manually enable it is use:
```c
...->SPIsetRegValue(RADIOLIB_SI443X_REG_MODULATION_MODE_CONTROL_2, RADIOLIB_SI443X_MODULATION_GFSK, 1, 0);
```

Below I provide to image of spectrum both from an SI4432 where it is clearly visible GFSK shaping is working
First is FSK, second GFSK

![fsk-si4432](https://user-images.githubusercontent.com/5026295/204981801-4b928c8d-57fc-4ff7-90f9-5d13d505ff9f.png)
g

![gfsk-si4432-2](https://user-images.githubusercontent.com/5026295/204981882-b1da7ba1-5f94-42a2-8869-46814e23f9dc.png)

**Comment by jgromes** [comment]
I think this can be implemented easily by extending the existing `setDataShaping()` method, I will take a look at it once I have a bit more time.

**Comment by jgromes** [comment]
GFSK support was added, you can now use `setDataShaping(RADIOLIB_SHAPING_0_5)` to enable GFSK.
