### ISSUE TITLE
RSSI not calculated correct on SX127x when SNR < 0

### ISSUE THREAD

**Issue by nseidle** [jgromes/RadioLib#640]
This is basically a nit but I believe [getRSSI()](https://github.com/jgromes/RadioLib/blob/master/src/modules/SX127x/SX1278.cpp#L388) is missing the 0.25.

    lastPacketRSSI += (lastPacketSNR * 0.25);

![image](https://user-images.githubusercontent.com/117102/206812103-99898712-3b80-499b-8112-081807b31ea2.png)

**Comment by jgromes** [comment]
Actually, I think that the `PacketSnr` in the above equations is supposed to be the raw value from register, and must be divided by 4 to get to the real value in dB. RadioLib uses the `getSNR` method, which already returns the processed value.

**Comment by nseidle** [comment]
Ah! Missed that. Thanks.
