### ISSUE TITLE
SX126x Class Reference states incorrect step size for setCurrentLimit API

### ISSUE THREAD

**Issue by MrSniffer** [jgromes/RadioLib#654]
In two places, the SX126x Class Reference says the setCurrentLimit step size is 0.25mA; it should state 2.5mA step size.

**Comment by jgromes** [comment]
Thanks for being so attentive! I found one of the instances (in SX126x.h), where is the second one?

**Comment by MrSniffer** [comment]
I was referring to the PDF document that describes the APIs. Perhaps both references are built from the .h file?

**Comment by jgromes** [comment]
I'm not sure which PDF you're referring to, there's the API reference on GitHub pages (https://jgromes.github.io/RadioLib/), which is built from the .h files by Doxygen.

**Comment by MrSniffer** [comment]
My bad; I was referring to my own PDF of the GitHub pages.
While you are at it, perhaps you should point out that the values must be >=0 and <= 140 mA.
Thanks for the edit you already made.

**Comment by jgromes** [comment]
True, most other configuration methods list the range, so it's added now.
