### ISSUE TITLE
Data garbled when receiving LoRa packets with SF6

### ISSUE THREAD

**Issue by RoelKroes** [jgromes/RadioLib#666]
Hello,

First, thanks for this awesome library! I already used it a lot with great success.

But now I ran into a problem which I am not able to solve:

I am trying to receive LoRa packets with an implicit header, spreading factor 6. However, whatever I do, the data keeps up ending garbled.  I cannot figure out what I am doing wrong. I can receive these SF6 packets on other receivers but not on my T-Beam with Radiolib. I use a T-Beam radio, version 5.6.0 of the library. All packets with other spreading factors (with explicit headers) are working correctly. 

I hope somebody can see the problem.

This is my full test code for receiving SF6 packets:

```C++
#include <RadioLib.h>
// I use a T-BEAM radio
#define PIN_NSS   18 
#define PIN_DIO0  26
#define PIN_RESET 23  
#define PIN_DIO1  33
#define PACKETLEN 255 // length of implicit header

SX1278 radio = new Module(PIN_NSS, PIN_DIO0, PIN_RESET, PIN_DIO1);

void setup() 
{
  Serial.begin(57600);
  Serial.println(F("[SX1278] Initializing ... "));
  int16_t state = radio.begin();

  radio.implicitHeader(PACKETLEN);
  radio.setFrequency(432.662);
  radio.setBandwidth(20.8);
  radio.setSpreadingFactor(6);
  radio.setCodingRate(5);
  radio.setSyncWord(0x12);
  radio.autoLDRO();
  // radio.setCRC(true);

  // set the function that will be called
  // when new packet is received
  radio.setDio0Action(setFlag);

  // start listening for LoRa packets
  Serial.println(F("[SX1278] Starting to listen ... "));
  state = radio.startReceive(PACKETLEN);  
}

// flag to indicate that a packet was received
volatile bool receivedFlag = false;
#if defined(ESP8266) || defined(ESP32)
  ICACHE_RAM_ATTR
#endif
void setFlag(void) {
  // we got a packet, set the flag
  receivedFlag = true;
}

void loop() {
  // check if the flag is set
  if(receivedFlag) {
    // reset flag
    receivedFlag = false;

    String str;
    int state = radio.readData(str,PACKETLEN);

    if (state == RADIOLIB_ERR_NONE) {
      // packet was successfully received
      Serial.println(F("[SX1278] Received packet!"));
      Serial.print("Bytes received: "); Serial.println(radio.getPacketLength());

      // print data of the packet
      Serial.print(F("[SX1278] Data:\t\t"));
      Serial.println(str);

    } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
      // packet was received, but is malformed
      Serial.println(F("[SX1278] CRC error!"));

    } else {
      // some other error occurred
      Serial.print(F("[SX1278] Failed, code "));
      Serial.println(state);

    }

    // put module back to listen mode
    radio.startReceive(PACKETLEN);
  }
}

```

This is the output I get on the serial monitor:

![serial_otput](https://user-images.githubusercontent.com/58561387/213172488-ba3af3bd-e7a7-4cd4-8260-089c34291755.png)

Thanks in advance,

Roel.

**Comment by jgromes** [comment]
I was able to reproduce this issue - it was actually an issue with internal handling of the fixed packet length.

Should be fixed in the latest commim, thanks for reporting!

**Comment by yefgabriel6690** [comment]
> Hello,
> 
> First, thanks for this awesome library! I already used it a lot with great success.
> 
> But now I ran into a problem which I am not able to solve:
> 
> I am trying to receive LoRa packets with an implicit header, spreading factor 6. However, whatever I do, the data keeps up ending garbled. I cannot figure out what I am doing wrong. I can receive these SF6 packets on other receivers but not on my T-Beam with Radiolib. I use a T-Beam radio, version 5.6.0 of the library. All packets with other spreading factors (with explicit headers) are working correctly.
> 
> I hope somebody can see the problem.
> 
> This is my full test code for receiving SF6 packets:
> 
> #include <RadioLib.h>
> // I use a T-BEAM radio
> #define PIN_NSS   18 
> #define PIN_DIO0  26
> #define PIN_RESET 23  
> #define PIN_DIO1  33
> #define PACKETLEN 255 // length of implicit header
> 
> SX1278 radio = new Module(PIN_NSS, PIN_DIO0, PIN_RESET, PIN_DIO1);
> 
> void setup() 
> {
>   Serial.begin(57600);
>   Serial.println(F("[SX1278] Initializing ... "));
>   int16_t state = radio.begin();
> 
>   radio.implicitHeader(PACKETLEN);
>   radio.setFrequency(432.662);
>   radio.setBandwidth(20.8);
>   radio.setSpreadingFactor(6);
>   radio.setCodingRate(5);
>   radio.setSyncWord(0x12);
>   radio.autoLDRO();
>   // radio.setCRC(true);
> 
>   // set the function that will be called
>   // when new packet is received
>   radio.setDio0Action(setFlag);
> 
>   // start listening for LoRa packets
>   Serial.println(F("[SX1278] Starting to listen ... "));
>   state = radio.startReceive(PACKETLEN);  
> }
> 
> // flag to indicate that a packet was received
> volatile bool receivedFlag = false;
> #if defined(ESP8266) || defined(ESP32)
>   ICACHE_RAM_ATTR
> #endif
> void setFlag(void) {
>   // we got a packet, set the flag
>   receivedFlag = true;
> }
> 
> void loop() {
>   // check if the flag is set
>   if(receivedFlag) {
>     // reset flag
>     receivedFlag = false;
> 
>     String str;
>     int state = radio.readData(str,PACKETLEN);
> 
>     if (state == RADIOLIB_ERR_NONE) {
>       // packet was successfully received
>       Serial.println(F("[SX1278] Received packet!"));
>       Serial.print("Bytes received: "); Serial.println(radio.getPacketLength());
> 
>       // print data of the packet
>       Serial.print(F("[SX1278] Data:\t\t"));
>       Serial.println(str);
> 
>     } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
>       // packet was received, but is malformed
>       Serial.println(F("[SX1278] CRC error!"));
> 
>     } else {
>       // some other error occurred
>       Serial.print(F("[SX1278] Failed, code "));
>       Serial.println(state);
> 
>     }
> 
>     // put module back to listen mode
>     radio.startReceive(PACKETLEN);
>   }
> }
> This is the output I get on the serial monitor:
> 
> ![serial_otput](https://user-images.githubusercontent.com/58561387/213172488-ba3af3bd-e7a7-4cd4-8260-089c34291755.png)
> 
> Thanks in advance,
> 
> Roel.



> Hello,
> 
> First, thanks for this awesome library! I already used it a lot with great success.
> 
> But now I ran into a problem which I am not able to solve:
> 
> I am trying to receive LoRa packets with an implicit header, spreading factor 6. However, whatever I do, the data keeps up ending garbled. I cannot figure out what I am doing wrong. I can receive these SF6 packets on other receivers but not on my T-Beam with Radiolib. I use a T-Beam radio, version 5.6.0 of the library. All packets with other spreading factors (with explicit headers) are working correctly.
> 
> I hope somebody can see the problem.
> 
> This is my full test code for receiving SF6 packets:
> 
> #include <RadioLib.h>
> // I use a T-BEAM radio
> #define PIN_NSS   18 
> #define PIN_DIO0  26
> #define PIN_RESET 23  
> #define PIN_DIO1  33
> #define PACKETLEN 255 // length of implicit header
> 
> SX1278 radio = new Module(PIN_NSS, PIN_DIO0, PIN_RESET, PIN_DIO1);
> 
> void setup() 
> {
>   Serial.begin(57600);
>   Serial.println(F("[SX1278] Initializing ... "));
>   int16_t state = radio.begin();
> 
>   radio.implicitHeader(PACKETLEN);
>   radio.setFrequency(432.662);
>   radio.setBandwidth(20.8);
>   radio.setSpreadingFactor(6);
>   radio.setCodingRate(5);
>   radio.setSyncWord(0x12);
>   radio.autoLDRO();
>   // radio.setCRC(true);
> 
>   // set the function that will be called
>   // when new packet is received
>   radio.setDio0Action(setFlag);
> 
>   // start listening for LoRa packets
>   Serial.println(F("[SX1278] Starting to listen ... "));
>   state = radio.startReceive(PACKETLEN);  
> }
> 
> // flag to indicate that a packet was received
> volatile bool receivedFlag = false;
> #if defined(ESP8266) || defined(ESP32)
>   ICACHE_RAM_ATTR
> #endif
> void setFlag(void) {
>   // we got a packet, set the flag
>   receivedFlag = true;
> }
> 
> void loop() {
>   // check if the flag is set
>   if(receivedFlag) {
>     // reset flag
>     receivedFlag = false;
> 
>     String str;
>     int state = radio.readData(str,PACKETLEN);
> 
>     if (state == RADIOLIB_ERR_NONE) {
>       // packet was successfully received
>       Serial.println(F("[SX1278] Received packet!"));
>       Serial.print("Bytes received: "); Serial.println(radio.getPacketLength());
> 
>       // print data of the packet
>       Serial.print(F("[SX1278] Data:\t\t"));
>       Serial.println(str);
> 
>     } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
>       // packet was received, but is malformed
>       Serial.println(F("[SX1278] CRC error!"));
> 
>     } else {
>       // some other error occurred
>       Serial.print(F("[SX1278] Failed, code "));
>       Serial.println(state);
> 
>     }
> 
>     // put module back to listen mode
>     radio.startReceive(PACKETLEN);
>   }
> }
> This is the output I get on the serial monitor:
> 
> ![serial_otput](https://user-images.githubusercontent.com/58561387/213172488-ba3af3bd-e7a7-4cd4-8260-089c34291755.png)
> 
> Thanks in advance,
> 
> Roel.

I be rob me and never give nothing of the package so fix this now
