### ISSUE TITLE
rtl_433 OOK device decoders

### ISSUE THREAD

**Issue by fazerlab** [jgromes/RadioLib#677]
Suggestion to include in Radiolib

A driver to decode radio transmissions from devices on the ISM bands (and other frequencies)

ESP32 Implementation
https://github.com/NorthernMan54/rtl_433_ESP
Original
https://github.com/merbanan/rtl_433

Maybe getting Radiolib more and more universal

**Comment by jgromes** [comment]
IMHO this doesn't make much sense - why redo the work that was already done by someone else? The rtl_433_ESP proejct already uses RadioLib internally, so what exactly would be the added value of supporting OOK decoding directly in RadioLib?

**Comment by fazerlab** [comment]
Make sense , you are right.
Thank you for your time.
