### ISSUE TITLE
stm32f103c8t6 not working properly

### ISSUE THREAD

**Issue by halukmy** [jgromes/RadioLib#681]
can you give some examples arduino and stm32f103c8t6?

**Comment by jgromes** [comment]
> stm32f103c8t6 not working properly

What does "not working properly mean"?

> can you give some examples arduino and stm32f103c8t6?

Sure - they are in the "examples" folder. If your environment and Arduino is set up correcty, the exampels will work out-of-the box.

Fill in the information requested by the issue template first, without it, it is nearly impossible to help you.
