### ISSUE TITLE
LoRa SF11 not working

### ISSUE THREAD

**Issue by maxklt** [jgromes/RadioLib#693]
Hello,

all spread factors work except for 11, if SF11 is selected, the message "test" is transmitted as "tP3�".
With all other spread factors (7, 8, 9, 10, 12) the communication works properly.

On the transmitter node the LoRa.h library is used, which also works fine with all my other LoRa devices and across all spread factors.

For the transmitter node I use the Heltec LoRa v2 board and for the receiver node v3.

Hopefully someone can help me, many thanks in advance!

```cpp
#include <Arduino.h>
#include <RadioLib.h>

volatile bool receivedFlag = false;
volatile bool enableInterrupt = true;
int state;

SX1262 radio = new Module(8, 14, 12, 13);

#if defined(ESP8266) || defined(ESP32)
  ICACHE_RAM_ATTR
#endif
void setFlag(void) {
  if(!enableInterrupt) {
    return;
  }
  receivedFlag = true;
}

void initialiseRF() {
  Serial.print(F("[SX1268] Initializing ... "));
  state = radio.begin(868, 125, 11, 5, 0x12, 10, 8);

  if (state == RADIOLIB_ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }

  radio.setDio1Action(setFlag);

  Serial.print(F("[SX1262] Starting to listen ... "));
  state = radio.startReceive();
  if (state == RADIOLIB_ERR_NONE) {
    Serial.println(F("success!"));
  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);
    while (true);
  }
}

void setup() {
  Serial.begin(115200);
  initialiseRF();
}

void onReceive() {
  enableInterrupt = false;
  receivedFlag = false;

  String str;
  int state = radio.readData(str);

  byte configPayloadArr[4];
  radio.readData(configPayloadArr, 4);

  Serial.println("--------------------");
  if (state == RADIOLIB_ERR_NONE) {
    Serial.print(F("[SX1262] Receiver:\t"));
    Serial.println(configPayloadArr[0]);
    Serial.print(F("[SX1262] Sender:\t"));
    Serial.println(configPayloadArr[1]);
    Serial.print(F("[SX1262] MSG-ID:\t"));
    Serial.println(configPayloadArr[2]);
    Serial.print(F("[SX1262] MSG-Length:\t"));
    Serial.println(configPayloadArr[3]);

    Serial.print(F("[SX1262] Data:\t\t"));
    str.remove(0, 4);
    Serial.println(str);

    Serial.print(F("[SX1262] RSSI:\t\t"));
    Serial.print(radio.getRSSI());
    Serial.println(F(" dBm"));

    Serial.print(F("[SX1262] SNR:\t\t"));
    Serial.print(radio.getSNR());
    Serial.println(F(" dB"));

  } else if (state == RADIOLIB_ERR_CRC_MISMATCH) {
    // packet was received, but is malformed
    Serial.println(F("CRC error!"));

  } else {
    Serial.print(F("failed, code "));
    Serial.println(state);

  }

  // put module back to listen mode
  radio.startReceive();

  // we're ready to receive more packets,
  // enable interrupt service routine
  enableInterrupt = true;
}

void loop() {
  if(receivedFlag) {
    onReceive();
  }
}
```

---

SF10 (Correct)
```
[SX1262] Receiver:      125
[SX1262] Sender:        75
[SX1262] MSG-ID:        168
[SX1262] MSG-Length:    4
[SX1262] Data:          Test
[SX1262] RSSI:          -7.00 dBm
[SX1262] SNR:           7.50 dB
```

---

SF11 (False)
```
[SX1262] Receiver:      125
[SX1262] Sender:        75
[SX1262] MSG-ID:        143
[SX1262] MSG-Length:    84
[SX1262] Data:          tP3�
[SX1262] RSSI:          -43.00 dBm
[SX1262] SNR:           9.50 dB
```
The correct output should look like the SF12 output:

---

SF12 (Correct)
```
[SX1262] Receiver:      125
[SX1262] Sender:        75
[SX1262] MSG-ID:        168
[SX1262] MSG-Length:    4
[SX1262] Data:          Test
[SX1262] RSSI:          -32.00 dBm
[SX1262] SNR:           6.50 dB
```

**Comment by jgromes** [comment]
I don't think this is an issue of the sprading factor (tested with two SX126x devices, both SF11 and works OK), but rather your usage of `readData` - you're calling the method twice, in order that seems very strange:

1. You call `readData` without length argument, therefore the method will attempt to read all the data that were received.
2. You call `readData` again, this time with length set to 4. I have to say I did not test the case when user tries to request more data after the buffer was emptied, so I don't really know what happens here.

The correct order of operations is to first find out the packet length, and only then read it. Since there seem to be binary data at the first 4 bytes (I'm guessing), you should everything as binary, since if one of those first bytes happens to be NULL, it will terminate the string:

```c++
byte buffer[64]; // or however large you need it
size_t len = radio.getPacketLength();
int state = radio.readData(buffer, len);
// buffer[0]...buffer[3] arbitrary data
// buffer[4+] string
```

As to why the other cases seem to work, I suspect some of the buffers are just overflowing - try adding a counter to the "Test" string so that subsequent packets are not the same, and see what happens.

**Comment by jgromes** [comment]
Thanks for testing, unfortunately I still cannot replicate this. I tried transmitting from SX1278, but still everything works correctly.

Could you try using RadioLib on the transmitter?

**Comment by maxklt** [comment]
It works now, but unfortunately I can't say what the problem was.
Thanks for your support!
