### ISSUE TITLE
Hellschreiber mode on RA02 (SX1278)

### ISSUE THREAD

**Issue by Pacjunk** [jgromes/RadioLib#695]
**Describe the bug**
I think the SX1278 module may not like the fix implemented for #659. When I try to transmit, I just get a continuous carrier, rather than the hellschreiber output. If I revert the library to 5.5.0, then everything works (for this module).

Maybe there needs to be a test for the standby warm.

**Additional info (please complete):**
 - MCU: [e.g. Arduino Uno, ESP8266 etc.] Arduino Pro Mini
 - Link to Arduino core: [e.g. https://github.com/stm32duino/Arduino_Core_STM32 when using official STM32 core. See readme for links to all supported cores]
 - Wireless module type [e.g. CC1101, SX1268, etc.] Aithinker RA02 (SX1278)
 - Arduino IDE version  [e.g. 1.8.5] 1.8.19
 - Library version [e.g. 3.0.0] 5.7.0

**Comment by jgromes** [comment]
Thanks, you are correct, there way indeed a missing `standby` implementation in the SX127x driver. Fixed and tested in the latest commit.
