### ISSUE TITLE
RA-01SC (LLCC68) module: wrong compare string leads to "failed, code -2" 

### ISSUE THREAD

**Issue by TuxxuT** [jgromes/RadioLib#707]
Hi guys,

I use the library in version v5.7.0 with the LoRa Module RA-01SC (Semtech LLCC68).

`// LLCC68 has the following connections:`
`// NSS pin:   D1`
`// DIO1 pin:  NC`
`// NRST pin:  D0`
`// BUSY pin:  D2`
`LLCC68 radio = new Module(D1, RADIOLIB_NC, D0, D2);`

Later in code, the radio.begin() call always abort with "failed, code -2" because of the wrong compare string "SX126%d" in the SX126x::findChip method.

For the LLCC68 module it should be "LLCC68"...
If I am reading the data at address 0x0320 I get a reponse "LLCC68 V2H 2H02" from the Semtech LLCC68.

This behavior should be checked and changed if necessary. I think this is currently due to the inheritance from the SX126x class.

**Comment by jgromes** [comment]
Thank you for reporting this, I was hoping I could get away with "SX126%d", but forgot LLCC68 is a thing. Fixed in the latest commit!
