### ISSUE TITLE
Contradiction between code and wiki

### ISSUE THREAD

**Issue by tinchopu** [jgromes/RadioLib#717]
According to

https://github.com/jgromes/RadioLib/blob/45c5859338590b7eede23cb2f95284c3fb0cf08e/examples/CC1101/CC1101_Receive/CC1101_Receive.ino#L26

GD02 is optional whereas in https://github.com/jgromes/RadioLib/wiki/Modules#sub-ghz-fsk-radio-module it is required- what should it be?

Thanks

**Comment by jgromes** [comment]
GDO0 is the pin that has to be connected, the wiki should be fixed now - thanks for reporting!
