### ISSUE TITLE
sx128x invertIQ functional?

### ISSUE THREAD

**Issue by K4KDR** [jgromes/RadioLib#724]
Greetings!

With sx127x devices, I see in 

`src/modules/SX127x/SX127x.h`

reference to the directive '**invertIQ**'

`int16_t invertIQ(bool invertIQ);`

which I am able to utilize in sketches successfully to set (or not set) the device to invert the received signals

![sx127x-invert](https://user-images.githubusercontent.com/19886368/230738390-cae1a779-c798-4c22-aa74-3be5819f9417.png)

... however, I don't understand the programming syntax well enough to understand how to accomplish the same thing with sx128x devices.

In

`src/modules/SX128x/SX128x.h`

... I see references to inverted -vs- non-inverted

![sx128x-invert](https://user-images.githubusercontent.com/19886368/230738438-56baffe7-779f-4982-9b24-fe1c1d088986.png)

... but I apologize in advance for not being able to figure out how to instruct the hardware to use one setting or the other.

When you have a rare spare moment, could I please get some direction on how to do that with **sx128x devices**?   Searching through the technical documentation & generic searches online have not given me anything to help.

Many thanks as always!

-Scott,  K4KDR

**Comment by jgromes** [comment]
Looks like IQ inversion was never implemented for SX128x, and for SX126x for that matter. I added both, though it's untested, so use with caution.

**Comment by K4KDR** [comment]
Thanks SO much!!

I'll try known signals and verify that it works one way & NOT the other.
