### ISSUE TITLE
SX1262 TransmitDirect？

### ISSUE THREAD

**Issue by Kerry-Huang** [jgromes/RadioLib#73]
Can this function be implemented in the SX1262 module? Looks like DIO2 is already occupied by the RF switch.

**Comment by jgromes** [comment]
transmitDirect is implemented on SX126x. Unlike SX127x however, there is no way to feed data to the module via DIO pins. The only thing transmitDirect on SX126x does is output continuous RF wave, which is used for RTTY and Morse code.

**Comment by viric** [comment]
The AX.25 AFSK example claims SX1262 can work: https://github.com/jgromes/RadioLib/blob/master/examples/AX25/AX25_Transmit_AFSK/AX25_Transmit_AFSK.ino#L51
