### ISSUE TITLE
On the problem of using cc1101 in pager example.

### ISSUE THREAD

**Issue by BG7UHS** [jgromes/RadioLib#742]
In the example of pager receiving, how does this pin specify the pin of cc1101?

state = pager.startReceive(pin, 1234567);

**Comment by jgromes** [comment]
Sorry, I have no idea what you're trying to say. Do you want to ask which pin of the CC1101 should you connect to your Arduino (or whatever you are using, you did not say) to receive pager transmissions? The answer ther would be GDO2.

**Comment by BG7UHS** [comment]
Thank you very much. I use cc1101 and arduino nano.
