### ISSUE TITLE
Is the HAL pinMode only used to direction?

### ISSUE THREAD

**Issue by nicklasb** [jgromes/RadioLib#745]
Hi!
 
I am creating a HAL for my framework, and it occurred to me that the only defined values for pinMode is input or output?
Shouldn't the pinMode then rather be pinDirection or something similar?

It would also be slightly more compatible to non-Arduino platforms, like ESP-IDF and STM32 where these are separate. 

I have just found the HAL for Arduino and PIO, so I am thinking that it would be all that breaking?

**Comment by jgromes** [comment]
The HAL was based on the parts of Arduino framework that were being used by the library - the library only used INPUT and OUTPUT macros, hence those two are the only ones accounted for in the HAL class. Things like INPUT_PULLUP or others (that are defined in some Arduino frameworks) weren't used.

What exactly are you missing?

**Comment by nicklasb** [comment]
Thanks for your response!

Basically, It'd be great if it was called what it is exactly used for; pinDirection, and had a boolean parameter. 
Handling the way more general pinMode, presents a way more complex hurdle when implementing a HAL if one doesn't get that it actually just have two possible values.

Not a big thing. I am partially also asking to make sure I don't have to handle a lot of other cases.

**Comment by jgromes** [comment]
Sorry, I don't understand how this would simplify things.

Let's assume the platform (e.g. STM32 HAL libraries) has more options than just input/output (for example: input + pull-up, input + pull-down, open-drain output etc.). To further complicate things, let's say that to configure pin for input, you have to call a different function that to configure it for output or any other of the options (not true for STM32 Hal, but let's stick with it).

When constructing your RadioLib HAL, you have to implement the `pinMode` method and set the the values of `RadioLibHal::GpioModeInput` and `RadioLibHal::GpioModeOutput`. The values you choose are up to you - they can be completely independent from the STM32 HAL. Then, in your imlpementation of `pinMode`, you have to check them and call the correct STM functions, something like this:

```c++
void pinMode(uint32_t pin, uint32_t mode) {
  if(pin == RADIOLIB_NC) {
    return;
  }

  // you also need some way to determine port just from pin
  uint8_t port = getPortFromPin(pin);
  
  if(mode == MY_INPUT_VALUE) {
    GPIO_InitTypeDef init = {
      .Pin = pin,
      .Mode = GPIO_MODE_INPUT,
      .Pull = GPIO_NOPULL,
      .Speed = GPIO_SPEED_FREQ_LOW,
      .Alternate = 0UL,
    };
    HAL_GPIO_Init(port, &init);
  } else {
    GPIO_InitTypeDef init = {
      .Pin = pin,
      .Mode = GPIO_MODE_OUTPUT_PP,
      .Pull = GPIO_NOPULL,
      .Speed = GPIO_SPEED_FREQ_LOW,
      .Alternate = 0UL,
    };
    HAL_GPIO_Init(port, &init);
  }
}
```

I don't understand how constraining the `mode` argument of `pinMode` to just two possible values would improve things. It would actually just make future changes harder, if at some point the library needs to use something else than input/output. But maybe I'm missing something in your use-case.

**Comment by nicklasb** [comment]
Hi, 

You are right, this is probably the best trade-off. 
This actually made me realize that one of my implementations was wrong; I had forgot that one of my set_direction-implementations was actually a quick-fix of my own, not of the framework. :-) 

Thanks, and sorry for sending you off the path a bit here, closing!

Kind regards, Nicklas

**Comment by jgromes** [comment]
No worries, it's good to re-evaluate previous design decisions once in a while ;)
