### ISSUE TITLE
DIO1ACTION for SX1262 still relies on default IRQ direction

### ISSUE THREAD

**Issue by MrSniffer** [jgromes/RadioLib#765]
The change log sez:
All methods to attach interrupts (e.g., setDioAction(), setGdoAction() etc.) no longer have a default level change direction.

This change does not appear to have been made for DIO1ACTION in  SX126x module, which is unchanged (code and examples.)

**Comment by jgromes** [comment]
See the following comment: https://github.com/jgromes/RadioLib/discussions/737#discussioncomment-5793085
