### ISSUE TITLE
433MHz Lora with cheap sensors-outlets

### ISSUE THREAD

**Issue by kiralikbeyin** [jgromes/RadioLib#8]
Can i listen 433MHz RF (cheap 433mhz door - motion sensors) or send (cheap on-off switches - outlets) with TTGO or Heltec Lora ESP32? Because RF Receive/send Modules are really crappy..

Heltec:
https://www.ebay.com/itm/SX1278-LoRa-ESP32-0-96-inch-Blue-ESP8266-OLED-Display-Bluetooth-WIFI-Lora-Kit-32-/282594201585

TTGO:
https://www.banggood.com/Wemos-TTGO-LORA-SX1278-ESP32-0_96OLED-16-Mt-Bytes-128-Mt-bit-433Mhz-For-Arduino-p-1205930.html?cur_warehouse=CN

433mhz rf link kit:
https://www.banggood.com/433Mhz-RF-Transmitter-With-Receiver-Kit-For-Arduino-ARM-MCU-Wireless-p-74102.html?utm_source=google&utm_medium=cpc_ods&utm_content=aurogon&utm_campaign=ele-sdsrm-Ardui&ad_id=329260116894&gclid=Cj0KCQiA2L7jBRCBARIsAPeAsaMsHOMf4KDD5M7iuqXYYhqQ035CX7sqz50SkuAJFiJ-K-bup2WaXnUaAkd3EALw_wcB&cur_warehouse=CN

**Comment by jgromes** [comment]
If I recall correctly those modules just transmit 433 MHz wave without any modulation. You can (in theory) use the FSK modem in direct mode to receive that (see the [FSKModem example](https://github.com/jgromes/LoRaLib/blob/master/examples/FSKModem/FSKModem.ino)), but I haven't tried it myself.
