### ISSUE TITLE
Incorrect preamble sync?

### ISSUE THREAD

**Issue by observator-x** [jgromes/RadioLib#82]
As far as i noticed using the FSK TX (defaults) of radiolib i should get/receive a preamble + sync of:

0x55,
0x2D, 0x01,

0123456789abcdefab5a (data+2byte crc)

but when i capture the packet i get:

0x2a, 0xaa, 0xaa, 0x96, 0x80, 0x84,

0123456789abcdefab5a (data+2byte crc)

what could be wrong? i use:

 - Modules [RFM95, ESP8266]
 - Arduino IDE version  [1.8.10]
-  Radiolib latest version

**Comment by jgromes** [comment]
You're right that 0x55 should be the default preamble value, just as the default sync word should be 0x2D01. What are you using to capture the packets?

**Comment by observator-x** [comment]
LIME-SDR and GNUradio

**Comment by jgromes** [comment]
That doesn't tell me a whole lot. Could you please share the exact setup? (blocks used, configuration etc.)?

Also, were you able to verify that the data is correct, for example with a known working transmitter?

**Comment by observator-x** [comment]
I receive the signal succesfully with another RFM95 with same setup, also when i record the IQ signal with the SDR and re-broadcast it it sucessfully received.  i can show you my current setup with UHR wich i have currently setup to receive the packets

**Comment by jgromes** [comment]
I checked the SPI registers relevant to this (SX127X_REG_SYNC_CONFIG and SX127X_REG_SYNC_VALUE_1 - SX127X_REG_SYNC_VALUE_8) and the values are the expected ones (preamble 0x55, sync word enabled, two bytes, 0x2D 0x01).

I think I know what's going on - you start decoding one bit too late, hence all your data is shifted one bit. That's how 0x55 preamble becomes 0xAA and how 0x2D01 turns into 0x9680. Assuming you're using the default configuration, there's also a length byte between sync word and data bytes. You sent 8 bytes of data, hence the length byte will be 0x08.

The shift is clearly visible here:
```
0x552D0108 = 01010101001011010000000100001000
0xAA968084 = 10101010100101101000000010000100
```

Also, I have RTL-SDR dongle and haven't used UHR before. Could you please share your configuration or point me towards an article/guide to decode FSK data using that software? It would be incredibly helpful in the future.
