### ISSUE TITLE
ESP2266WemosD1 Moudle.cpp compile issue

### ISSUE THREAD

**Issue by skip375** [jgromes/RadioLib#825]
When attempting to try Wemos ESP8266 mini D1 board in Arduino IDE.
A compiler issues a error:

//        c:\Users\\Arduino\libraries\RadioLib\src\Module.cpp:406:23: error: expected ')' before '__INT32'

        406 |     sprintf(str, "%07" PRIx32 "  ", i+offset);
               |            ~          ^
               |                       )

Not showstopper but thought that i would report it

**Comment by jgromes** [comment]
Thank you for the report, however, this is not sufficient for me to reproduce this, I can build an example sketch for the Wemos D1 without issues. Not even explicitly calling `Module::hexdump` in the sketch file causes this.

So pleae fill in the information requested by the [bug report issue template](https://github.com/jgromes/RadioLib/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by jgromes** [comment]
Closed due to inactivity
