### ISSUE TITLE
How to Get Data/Bit Rate for SX1280 in FLRC Mode

### ISSUE THREAD

**Issue by Yash-Varuni** [jgromes/RadioLib#831]
### How to Get Data/Bit Rate in SX1280 in FLRC Mode
I have Used SX1268, where I can use radio.getDataRate() to get the Data Transmit Rate, but when I use it for SX1280 FLRC Modem compile show error message error: 'class SX1280' has no member named 'getDataRate'.

**Comment by jgromes** [comment]
Closing as duplicate of discussion #830
