### ISSUE TITLE
LoRaWAN: implement LinkCheck and TimeReq

### ISSUE THREAD

**Issue by StevenCellist** [jgromes/RadioLib#913]
Currently, the two MAC commands that should be available to a LoRaWAN enduser are not implemented (LinkCheck to retrieve margin and gateway count, and TimeReq to retrieve the datetime).
I plan to add this in early January.

**Comment by StevenCellist** [comment]
![image](https://github.com/jgromes/RadioLib/assets/47155822/822e31b8-a8d7-4dcf-a5d4-01554ed490ed)
Two birds with one stone.. requesting the device to send the MAC requests using the Verification suite that I am also implementing. Which can manipulate the device through downlink commands. More later...

**Comment by jgromes** [comment]
@StevenCellist this was resolved by merging #918 and can be closed, right?

**Comment by StevenCellist** [comment]
Yes! Fully working.
