### ISSUE TITLE
sx1280 (e28-2g4m12s) and NUCLEO32 boards Issue

### ISSUE THREAD

**Issue by acunipisa** [jgromes/RadioLib#926]
Hi,

I have an issue with stm nucleo32 boards and the e28-2g4m12s (sx1280) module from ebyte. The module is working correctly with esp32.
The module can't communicate with the board, and I am afraid is something related to SPI (but not sure). Indeed, when I try to initialize the module (or sending commands), some SPI signals are off, meaning that they are not always sent from the MCU to the module and vice versa. (checked through o-scope). Specifically, in stm32f303k8, the sck line is always low.

I have already checked the documentation of these boards, removing the jumpers needed to separate D5 and D4 from A5 and A4, together with the LED on D13.

I tried 3 modules (1 of them was a 20s version), and several boards of the same kind, but the result is always the same.

Can u help me in solving this issue?

Thank you for your time and support,

Andrea

**Sketch that is causing the module fail**

```c++
#include <RadioLib.h>

const uint8_t SX1280_NSS = SS;     // Chip Select for the SPI interface, or D10
const uint8_t SX1280_RESET = D3;   // Reset pin for the SX1280
const uint8_t SX1280_BUSY = D6;    // Busy pin for the SX1280
const uint8_t SX1280_DIO1 = D4;    // Interrupt pin for DIO1

const uint8_t SX1280_RX_EN = D2;
const uint8_t SX1280_TX_EN = D3;

SX1280 radio = new Module(SX1280_NSS, SX1280_DIO1, SX1280_RESET, SX1280_BUSY);

void setup() {
  Serial.begin(115200);
  radioConfig();


}

void loop() {
  radioConfig();
  delay(1000);
}

void radioConfig(void) {
  int state = radio.beginFLRC();

  if (state == RADIOLIB_ERR_NONE) {
    // Success
  } else {
    // Fail
  }

  uint8_t syncWord[] = { 0x01, 0x23, 0x45, 0x67 };
  state = radio.setSyncWord(syncWord, 4); // just testing
}

```

**Hardware setup**

The setup is straightforward: a nucleo32 board from stm32 connected with 3.3V / GND and:
// Define pin mappings
const uint8_t SX1280_NSS = SS;     // Chip Select for the SPI interface, or D10
const uint8_t SX1280_SCK = SCK;    // SPI Clock, or D13
const uint8_t SX1280_MISO = MISO;  // SPI MISO, or D12
const uint8_t SX1280_MOSI = MOSI;  // SPI MOSI, od D11
const uint8_t SX1280_RESET = D3;   // Reset pin for the SX1280
const uint8_t SX1280_BUSY = D6;    // Busy pin for the SX1280
const uint8_t SX1280_DIO1 = D4;    // Interrupt pin for DIO1

**Debug mode output**
16:32:57.995 -> RadioLib Debug Info
16:32:57.995 -> Version:  6.3.0.0
16:32:57.995 -> Platform: Arduino STM32 (official)
16:32:57.995 -> Compiled: Jan 12 2024 16:10:27
16:32:57.995 -> 
16:32:57.995 -> M	SX128x
16:32:57.995 -> CMDW	80	
16:32:57.995 -> SI	0	
16:32:57.995 -> SO	FF	
16:32:58.999 -> GPIO pre-transfer timeout, is it connected?
16:33:00.019 -> GPIO pre-transfer timeout, is it connected?
16:33:01.025 -> GPIO pre-transfer timeout, is it connected?
16:33:02.032 -> GPIO pre-transfer timeout, is it connected?

**Additional info (please complete):**
 - MCU: stm32L432KC (& stm32F303K8), nucleo32 boards
 - Link to Arduino core: https://github.com/stm32duino/Arduino_Core_STM32 
 - Wireless module type: e28-2g4m12s (ebyte) - sx1280
 - Arduino IDE version: 2.2.1
 - Library version: 6.6.3

**Comment by jgromes** [comment]
These lines in the debug output are qutie telling:

```
16:32:57.995 -> SI 0
16:32:57.995 -> SO FF
```

MISO reading 0xFF is typical of a disconnected SPI bus. So my guess would be a wiring or SPI configruation issue.
