### ISSUE TITLE
Radiolib fails to build with -DRADIOLIB_EXCLUDE_SX1231

### ISSUE THREAD

**Issue by jp-bennett** [jgromes/RadioLib#929]
Troubleshooting build failures with Meshtastic and RadioLib 6.4.0. At my initial look, it seems like RadioLib fails to build when -DRADIOLIB_EXCLUDE_SX1231 is set. 

```In file included from .pio/libdeps/rak11200/RadioLib/src/RadioLib.h:88,
                 from src/mesh/RadioLibInterface.h:7,
                 from src/mesh/SX126xInterface.h:3,
                 from src/mesh/LLCC68Interface.h:3,
                 from src/main.cpp:57:
.pio/libdeps/rak11200/RadioLib/src/modules/SX123x/SX1233.h:23:30: error: expected class-name before '{' token
 class SX1233: public SX1231  {
                              ^```

**Comment by jgromes** [comment]
@jp-bennett thanks for reporting! I pushed a fix; if you want to stick weith the 6.4.0 release, you should be able to use `-DRADIOLIB_EXCLUDE_SX1233` together with `-DRADIOLIB_EXCLUDE_SX1231` as a workaround.
