### ISSUE TITLE
LoRaWAN Downlink

### ISSUE THREAD

**Issue by DavidKrepzi** [jgromes/RadioLib#957]
I plan to use RadioLib for receiving a LoRaWAN downlink transmission. I'm using the latest version of the library (6.4.2) on the Arduino side, along with its example file for uplink communication. I'm also using the same file for downlink reception. Downlink reception with RadioLib is reliable—the exact number of bytes sent from the Network Server (NS) is received on the end-device side. However, the downlink payloads appear different. I believe the downlink content is still either encrypted or encoded, and further decryption or decoding seems necessary.

I'm using a standard LoRaWAN NS at Actility ThingPark, so the process should be similar to using TTN and similar platforms.

Has anyone successfully received the same downlink payload sent from the NS at the end-device side? What additional steps are necessary? I'm using an ESP32 MCU with an SX1262 radio for testing. Registration works fine, and uplinks are received at the Actility NS. Downlinks are received at the end-device side, but the payload is illegible so far.

The code responsible for downlink reception is as follows:

```c++


state = node.downlink(strDown);
    
if (state == RADIOLIB_ERR_NONE) {
    Serial.println(F("Downlink Received!"));
    Serial.print(F("[Downlink] Data:\t\t"));       

    // Print the downlink data as a hexadecimal string
    Serial.print(F("[Downlink] Hex form:\t\t"));
    for (int i = 0; i < strDown.length(); i++) {
        char ch = strDown.charAt(i);
        // Print each byte as a two-digit hexadecimal number
        if ((uint8_t)ch < 0x10) Serial.print("0");
        Serial.print((uint8_t)ch, HEX);
    }
    Serial.println();  

    // Print the length of the downlink data
    Serial.print(F("[Downlink] Length:\t\t"));
    Serial.println(strDown.length());

    Serial.print(F("[Downlink] RSSI:\t\t"));
    Serial.print(radio.getRSSI());
    Serial.println(F(" dBm"));
    Serial.print(F("[Downlink] SNR:\t\t"));
    Serial.print(radio.getSNR());
    Serial.println(F(" dB"));
    Serial.print(F("[Downlink] Frequency error:\t"));
    Serial.print(radio.getFrequencyError());
    Serial.println(F(" Hz"));

} else if (state == RADIOLIB_ERR_RX_TIMEOUT) {
    Serial.println(F("Downlink timeout!"));

} else {
    Serial.print(F("Downlink failed, code "));
    Serial.println(state);
}


```

**Comment by HeadBoffin** [comment]
Could you share the bytes you send and the bytes you receive please.

> along with its example file for uplink communication. I'm also using the same file for downlink reception. 

Be aware that you have to use the same file - for Class A configs (the vast majority) a downlink is ONLY sent after an uplink.

**Comment by DavidKrepzi** [comment]
Thanks for looking into this.  Yes, I receive the downlinks only after an uplink. 

I schedule a downlink of "DEADBEEF" at the Actility side. I receive exactly 4 bytes worth downlink payload from the end-device. However, the received payload changes with each downlink although same payload is sent from NS side.  Would it be because some encryption is happening on the downlink payload, and its not yet decrypted?

**Comment by StevenCellist** [comment]
I've sent multiple handfuls of downlinks by now and never noticed any trouble. Can you enable debug mode (pretty please _not_ verbose mode) and show the output on your device when one or two downlinks occur?

**Comment by HeadBoffin** [comment]
Just doing a sanity check / test on the downlink - I'm not a fan of Strings and Strings for a byte array is particularly messy so I'm just reworking it for the other downlink function signature.

**Comment by HeadBoffin** [comment]
Try this:

```
uint8_t downlinkPayload[32];
size_t downlinkLength;
state = node.downlink(downlinkPayload, &downlinkLength);
if(state == RADIOLIB_ERR_NONE) {
      if(downlinkLength > 0) {
            Serial.print(F("[LoRaWAN] Downlink:\t"));
            Module::hexdump(downlinkPayload, downlinkLength);
      }
}
```

Your `DEADBEEF` should be revealed and you can interpret the `downlinkPayload` byte array

**Comment by HeadBoffin** [comment]
>             Module::hexdump(downlinkPayload, downlinkLength);

Should have added, you need RADIOLIB_DEBUG turned on for this to work, otherwise it won't compile. 

I'm working on a more modular example so will figure the debug output shortly.

**Comment by HeadBoffin** [comment]
@DavidKrepzi, did this solve your issue?

**Comment by HeadBoffin** [comment]
Assuming this worked for OP so closing.
