### ISSUE TITLE
Wiki correction, E22-900M30S

### ISSUE THREAD

**Issue by S5NC** [jgromes/RadioLib#975]
The E22-900M30S only uses the last stage of the PA, so the gain is more lik 7.25 dB (SX1262 output power level dependent). See https://github.com/S5NC/EBYTE_ESP32-S3/blob/main/power%20testing.txt

Also, the E22-900M33S is now available, but requires SX1262 output power to not exceed 9 dBm. I have not tested it, it will likely require a larger PA ramp up time. E22-400M33S is also available, though it was release much before.

You list the E220-900T30D but this doesn't support SPI, only a limited interface via UART, perhaps you meant the E220-900M30S?

**Comment by jgromes** [comment]
@S5NC thank you - I updated the Wiki accordingly.
